#!/usr/bin/env python3
from __future__ import annotations
import json, re
from pathlib import Path
from pypinyin import lazy_pinyin, Style

ROOT = Path(__file__).resolve().parents[1]
READING = ROOT / 'data' / 'reading'


def pinyin(text: str) -> str:
    parts = lazy_pinyin(text, style=Style.TONE, neutral_tone_with_five=False, errors=lambda x: list(x))
    out = ' '.join(parts)
    out = re.sub(r'\s+([，。！？；：、“”‘’（）《》])', r'\1', out)
    out = re.sub(r'([“‘（《])\s+', r'\1', out)
    return out[:1].upper() + out[1:] if out else ''


def han_count(text: str) -> int:
    return len(re.findall(r'[\u3400-\u9fff]', text))


def make(level: int, slug: str, title: str, topic: str, target: int, pairs: list[tuple[str,str]]) -> dict:
    total = han_count(''.join(x[0] for x in pairs))
    return {
        'id': f'READ-L{level}-{slug}',
        'level': str(level),
        'title': title,
        'topic': topic,
        'targetCharacters': target,
        'actualCharacters': total,
        'sentences': [
            {'id': f'READ-L{level}-{slug}-S{i+1:02d}', 'zh': zh, 'pinyin': pinyin(zh), 'vi': vi}
            for i, (zh, vi) in enumerate(pairs)
        ]
    }

HSK6 = [
('public-space','Không gian công cộng và chất lượng đô thị','đô thị',[
('一座城市是否宜居，不能只看道路是否宽阔、建筑是否新颖，还要看普通人能不能方便地找到安全、舒适并且愿意停留的公共空间。','Một thành phố có đáng sống hay không không chỉ phụ thuộc đường sá rộng hay công trình mới, mà còn ở việc người bình thường có dễ tìm được không gian công cộng an toàn, thoải mái và muốn ở lại hay không.'),
('公园、广场、图书馆、河边步道和社区活动室，看似不直接创造利润，却持续影响居民的健康、交往方式和对城市的归属感。','Công viên, quảng trường, thư viện, đường ven sông và phòng sinh hoạt cộng đồng tuy không trực tiếp tạo lợi nhuận nhưng liên tục ảnh hưởng sức khỏe, cách giao tiếp và cảm giác thuộc về thành phố của cư dân.'),
('当一个社区缺少可以坐下、散步和交流的地方时，人们往往只能在家、办公室和商业场所之间移动。','Khi cộng đồng thiếu nơi có thể ngồi, đi bộ và trò chuyện, mọi người thường chỉ di chuyển giữa nhà, văn phòng và khu thương mại.'),
('这种生活虽然效率很高，却容易使邻里关系变得陌生，也让老人、儿童和行动不便者更难参与公共生活。','Lối sống này tuy hiệu quả nhưng dễ làm quan hệ láng giềng xa lạ và khiến người già, trẻ em, người hạn chế vận động khó tham gia đời sống công cộng hơn.'),
('好的公共空间首先需要可达性，也就是说，人们不必开车很远，就能通过步行、骑车或公共交通到达。','Không gian công cộng tốt trước hết cần dễ tiếp cận, nghĩa là mọi người không phải lái xe xa mà có thể đi bộ, đạp xe hoặc dùng giao thông công cộng để đến.'),
('其次，设计必须考虑不同年龄和身体条件，而不是只满足年轻、健康、消费能力较强的人。','Thứ hai, thiết kế phải tính đến các độ tuổi và điều kiện cơ thể khác nhau, chứ không chỉ phục vụ người trẻ, khỏe và có khả năng chi tiêu cao.'),
('一条没有树荫的长路，在地图上可能距离很短，对夏天带孩子出门的家长来说却并不友好。','Một con đường dài không có bóng cây trên bản đồ có thể trông rất gần, nhưng lại không thân thiện với phụ huynh đưa trẻ ra ngoài vào mùa hè.'),
('同样，如果座椅太少、厕所难找、夜间照明不足，许多人会被无形地排除在外。','Tương tự, nếu thiếu ghế, khó tìm nhà vệ sinh hoặc ánh sáng ban đêm không đủ, nhiều người sẽ bị loại trừ một cách vô hình.'),
('公共空间还需要一定程度的开放性，让使用者可以根据自己的需要进行阅读、运动、聊天或安静休息。','Không gian công cộng cũng cần mức độ mở nhất định để người dùng có thể đọc sách, vận động, trò chuyện hoặc nghỉ yên tĩnh theo nhu cầu.'),
('如果每一块空地都被安排成单一用途，或者只有付费消费才能进入，空间就很难真正属于公众。','Nếu mọi khoảng trống đều bị quy định một mục đích duy nhất, hoặc chỉ vào được khi trả phí tiêu dùng, không gian khó thực sự thuộc về công chúng.'),
('当然，开放并不意味着没有管理。','Tất nhiên, mở không có nghĩa là không quản lý.'),
('噪声、垃圾、安全和不同活动之间的冲突，都需要清楚的规则与长期维护。','Tiếng ồn, rác, an toàn và xung đột giữa các hoạt động đều cần quy tắc rõ ràng và bảo trì lâu dài.'),
('问题在于，管理不应只依靠禁止，而应通过合理分区、时间安排和现场沟通来寻找平衡。','Vấn đề là quản lý không nên chỉ dựa vào cấm đoán mà cần tìm cân bằng qua phân khu hợp lý, sắp xếp thời gian và giao tiếp tại chỗ.'),
('在规划过程中，居民的经验非常重要，因为他们最了解哪些路线危险、哪些角落长期闲置，以及哪些设施真正被使用。','Trong quy hoạch, kinh nghiệm của cư dân rất quan trọng vì họ hiểu nhất tuyến nào nguy hiểm, góc nào bị bỏ trống lâu và cơ sở nào thực sự được dùng.'),
('如果意见征集只是形式，最终方案仍由少数人决定，公共空间就可能漂亮却不实用。','Nếu lấy ý kiến chỉ mang tính hình thức và phương án cuối vẫn do số ít quyết định, không gian có thể đẹp nhưng không thực dụng.'),
('相反，当居民参与设计、管理甚至日常活动时，他们更愿意共同维护环境，也更容易形成信任。','Ngược lại, khi cư dân tham gia thiết kế, quản lý và cả hoạt động hằng ngày, họ sẵn sàng cùng giữ gìn môi trường và dễ hình thành niềm tin hơn.'),
('近年来，一些城市把停车位改成小型花园，把废弃铁路改成步道，说明改善公共生活不一定需要大规模建设。','Những năm gần đây, một số thành phố biến chỗ đỗ xe thành vườn nhỏ, đường sắt bỏ hoang thành lối đi, cho thấy cải thiện đời sống công cộng không nhất thiết cần xây dựng quy mô lớn.'),
('有时，增加几棵树、几张长椅和一处可以避雨的地方，就能明显改变人们使用街道的方式。','Đôi khi chỉ cần thêm vài cây, vài ghế dài và một chỗ trú mưa đã có thể thay đổi rõ cách mọi người sử dụng đường phố.'),
('评估公共空间也不能只看开幕当天的人数，而要观察它在不同季节、不同时间和不同群体中的实际使用情况。','Đánh giá không gian công cộng cũng không thể chỉ nhìn số người ngày khai trương mà phải quan sát việc sử dụng thực tế ở các mùa, thời điểm và nhóm người khác nhau.'),
('真正成功的空间往往并不追求夸张的外观，而是让人感到自然、方便，并愿意一再回来。','Không gian thực sự thành công thường không chạy theo vẻ ngoài phô trương mà khiến người ta thấy tự nhiên, thuận tiện và muốn quay lại nhiều lần.'),
('从这个角度看，公共空间不是城市剩余土地的装饰，而是连接陌生人、支持日常生活并体现公共价值的重要基础。','Từ góc độ này, không gian công cộng không phải vật trang trí cho đất thừa của thành phố mà là nền tảng quan trọng kết nối người lạ, hỗ trợ đời sống hằng ngày và thể hiện giá trị công cộng.'),
('一座愿意为步行者、孩子和老人保留空间的城市，也是在表达它如何理解发展与尊严。','Một thành phố sẵn sàng giữ không gian cho người đi bộ, trẻ em và người già cũng đang thể hiện cách nó hiểu về phát triển và phẩm giá.'),
],1000),
('ai-learning','AI trong học tập và năng lực phán đoán','giáo dục',[
('生成式人工智能进入学校以后，许多学生第一次发现，原来整理资料、修改语言甚至完成一篇结构完整的文章，都可以在很短时间内得到帮助。','Sau khi AI tạo sinh vào trường học, nhiều học sinh lần đầu nhận ra việc tổng hợp tài liệu, sửa ngôn ngữ hay hoàn thành một bài viết có cấu trúc đều có thể được hỗ trợ rất nhanh.'),
('这种工具降低了表达门槛，也让学习者能够随时提出问题，获得不同角度的解释。','Công cụ này hạ thấp rào cản biểu đạt và cho phép người học đặt câu hỏi bất cứ lúc nào để nhận giải thích từ nhiều góc độ.'),
('对于不敢在课堂上发言的人来说，它甚至提供了一种相对没有压力的练习环境。','Với người ngại phát biểu trên lớp, nó còn tạo ra môi trường luyện tập tương đối ít áp lực.'),
('然而，便利越明显，越需要重新思考学习究竟意味着什么。','Tuy nhiên, càng tiện lợi càng cần suy nghĩ lại việc học thực sự có nghĩa gì.'),
('如果学生只把任务交给系统，再直接提交生成的结果，他们可能得到一份看起来不错的作业，却没有经历理解、选择和修改的过程。','Nếu học sinh chỉ giao nhiệm vụ cho hệ thống rồi nộp thẳng kết quả, họ có thể có một bài trông tốt nhưng không trải qua quá trình hiểu, lựa chọn và chỉnh sửa.'),
('长期如此，语言能力、问题意识和独立判断都可能停留在表面。','Nếu kéo dài, năng lực ngôn ngữ, ý thức vấn đề và phán đoán độc lập có thể chỉ dừng ở bề mặt.'),
('人工智能给出的答案还可能包含错误、过时信息或没有依据的细节。','Câu trả lời của AI còn có thể chứa lỗi, thông tin lỗi thời hoặc chi tiết không có căn cứ.'),
('它通常会用流畅而自信的语言表达，因此错误并不总是容易被发现。','Nó thường diễn đạt trôi chảy và tự tin nên lỗi không phải lúc nào cũng dễ phát hiện.'),
('这说明，使用工具的核心能力不是会不会输入提示，而是能不能检查来源、比较观点并判断结果是否适合当前情境。','Điều này cho thấy năng lực cốt lõi không phải biết nhập prompt hay không, mà là có kiểm tra nguồn, so sánh quan điểm và phán đoán kết quả có phù hợp bối cảnh hay không.'),
('教师也需要调整作业设计。','Giáo viên cũng cần điều chỉnh thiết kế bài tập.'),
('如果题目只要求重复公开资料，学生当然容易让系统代替自己完成。','Nếu đề chỉ yêu cầu lặp lại tài liệu công khai, học sinh đương nhiên dễ để hệ thống làm thay.'),
('更有价值的任务可以要求学生结合个人观察、展示修改过程、解释选择理由，或者在课堂上回应追问。','Nhiệm vụ có giá trị hơn có thể yêu cầu kết hợp quan sát cá nhân, trình bày quá trình sửa, giải thích lý do lựa chọn hoặc trả lời câu hỏi tiếp theo trên lớp.'),
('这样一来，人工智能可以参与准备，却不能完全替代思考。','Như vậy AI có thể tham gia chuẩn bị nhưng không thể thay thế hoàn toàn suy nghĩ.'),
('学校还应明确哪些使用方式可以接受，哪些情况必须说明工具参与，以及如何保护学生输入的数据。','Trường học cũng cần làm rõ cách dùng nào được chấp nhận, trường hợp nào phải khai báo sự tham gia của công cụ và cách bảo vệ dữ liệu học sinh nhập vào.'),
('单纯禁止往往难以执行，因为学生在校外仍然可以接触这些工具。','Cấm hoàn toàn thường khó thực hiện vì học sinh vẫn có thể tiếp cận công cụ ngoài trường.'),
('比禁止更重要的是建立透明规则，并让学生理解诚实、署名和责任为什么重要。','Quan trọng hơn cấm đoán là xây dựng quy tắc minh bạch và giúp học sinh hiểu vì sao trung thực, ghi nguồn và trách nhiệm quan trọng.'),
('在语言学习中，人工智能可以扮演练习伙伴，帮助纠正句子、模拟对话或提供适合水平的阅读材料。','Trong học ngôn ngữ, AI có thể làm bạn luyện tập, giúp sửa câu, mô phỏng hội thoại hoặc cung cấp bài đọc phù hợp trình độ.'),
('但学习者仍需要亲自开口、回忆词语、承受暂时说不出来的不适，因为这些困难正是能力形成的一部分。','Nhưng người học vẫn cần tự nói, nhớ lại từ và chịu cảm giác tạm thời không diễn đạt được, vì những khó khăn đó là một phần của quá trình hình thành năng lực.'),
('合理的做法不是拒绝技术，也不是把技术当成万能答案，而是为不同学习目标选择不同程度的支持。','Cách hợp lý không phải từ chối công nghệ hay coi nó là đáp án vạn năng, mà là chọn mức hỗ trợ khác nhau cho từng mục tiêu học.'),
('当目标是获得灵感时，可以让系统提供多个方向；当目标是训练写作时，则应保留独立起草和修改的阶段。','Khi mục tiêu là tìm ý tưởng, có thể để hệ thống đưa nhiều hướng; khi mục tiêu là luyện viết, cần giữ giai đoạn tự viết nháp và chỉnh sửa.'),
('教育真正需要保护的，不是某一种传统做法，而是学习者提出问题、理解证据、承担判断后果的能力。','Điều giáo dục thực sự cần bảo vệ không phải một cách làm truyền thống nào, mà là năng lực đặt câu hỏi, hiểu bằng chứng và chịu trách nhiệm cho phán đoán.'),
('只有当工具帮助人变得更主动、更诚实和更有判断力时，它才算真正改善了学习。','Chỉ khi công cụ giúp con người chủ động, trung thực và có khả năng phán đoán hơn, nó mới thực sự cải thiện việc học.'),
],1000),
('aging','Xã hội già hóa và hợp tác giữa các thế hệ','xã hội',[
('许多国家正在进入人口老龄化阶段，老年人口增加、出生率下降以及家庭规模缩小，正在同时改变医疗、住房、就业和照护制度。','Nhiều quốc gia đang bước vào giai đoạn già hóa; dân số cao tuổi tăng, tỷ lệ sinh giảm và quy mô gia đình thu nhỏ đang đồng thời thay đổi y tế, nhà ở, việc làm và chăm sóc.'),
('讨论老龄化时，人们常把它描述成沉重负担，好像年龄增长只意味着疾病、依赖和社会成本。','Khi bàn về già hóa, người ta thường mô tả như gánh nặng, như thể tuổi tăng chỉ đồng nghĩa bệnh tật, phụ thuộc và chi phí xã hội.'),
('这种说法忽略了老年人的经验、劳动能力、家庭贡献和继续学习的愿望。','Cách nói này bỏ qua kinh nghiệm, khả năng lao động, đóng góp gia đình và mong muốn tiếp tục học của người cao tuổi.'),
('事实上，六十多岁的人可能仍然健康活跃，而同一年龄的人也可能因为职业、收入和生活环境不同，面临完全不同的需要。','Thực tế, người ngoài sáu mươi có thể vẫn khỏe và năng động, trong khi người cùng tuổi có thể có nhu cầu hoàn toàn khác do nghề nghiệp, thu nhập và môi trường sống.'),
('因此，政策不能只按照年龄划分群体，而应关注真实的身体状况和生活条件。','Vì vậy, chính sách không nên chỉ chia nhóm theo tuổi mà cần chú ý tình trạng cơ thể và điều kiện sống thực tế.'),
('首先，城市和住宅需要更适合长期居住。','Trước hết, thành phố và nhà ở cần phù hợp hơn cho việc sống lâu dài.'),
('没有电梯的高层住宅、过快的交通信号和缺少座椅的人行道，会把许多老人困在家中。','Nhà cao tầng không thang máy, đèn giao thông quá nhanh và vỉa hè thiếu ghế có thể khiến nhiều người già bị kẹt trong nhà.'),
('改善无障碍设施不仅帮助老人，也方便推婴儿车的家长、暂时受伤的人和携带行李的旅客。','Cải thiện tiếp cận không chỉ giúp người già mà còn thuận tiện cho phụ huynh đẩy xe trẻ em, người tạm bị thương và khách mang hành lý.'),
('其次，照护责任不能完全落在家庭成员，尤其不能默认由女性无偿承担。','Thứ hai, trách nhiệm chăm sóc không thể hoàn toàn đổ lên gia đình, đặc biệt không thể mặc định phụ nữ làm không công.'),
('公共护理服务、灵活工作制度和对照护者的经济支持，可以减少家庭内部的压力。','Dịch vụ chăm sóc công, chế độ làm việc linh hoạt và hỗ trợ tài chính cho người chăm sóc có thể giảm áp lực trong gia đình.'),
('同时，专业护理人员需要合理工资和培训，否则服务质量难以稳定。','Đồng thời, nhân viên chăm sóc chuyên nghiệp cần lương và đào tạo hợp lý, nếu không chất lượng dịch vụ khó ổn định.'),
('就业制度也应提供更多选择。','Chế độ việc làm cũng cần nhiều lựa chọn hơn.'),
('有些人希望延迟退休并继续发挥专业经验，有些人则因为长期从事体力劳动而需要更早休息。','Có người muốn nghỉ hưu muộn để tiếp tục phát huy kinh nghiệm chuyên môn, có người do lao động thể lực lâu năm cần nghỉ sớm hơn.'),
('统一的安排看似公平，却可能忽视不同职业之间的巨大差异。','Một sắp xếp thống nhất tưởng công bằng nhưng có thể bỏ qua khác biệt lớn giữa các nghề.'),
('更灵活的退休方式、兼职机会和终身学习项目，能够让个人根据情况作出选择。','Cách nghỉ hưu linh hoạt hơn, cơ hội bán thời gian và chương trình học suốt đời giúp cá nhân lựa chọn theo hoàn cảnh.'),
('老龄化社会还需要促进代际交流，而不是把不同年龄的人分开。','Xã hội già hóa còn cần thúc đẩy giao lưu giữa các thế hệ thay vì tách người khác tuổi.'),
('社区可以组织技能交换，让年轻人帮助老人使用数字服务，老人则分享手艺、职业经验或地方记忆。','Cộng đồng có thể tổ chức trao đổi kỹ năng: người trẻ giúp người già dùng dịch vụ số, người già chia sẻ nghề thủ công, kinh nghiệm nghề nghiệp hoặc ký ức địa phương.'),
('这样的合作能减少偏见，也让双方认识到彼此并不是竞争资源的对手。','Sự hợp tác này giảm định kiến và giúp hai bên nhận ra họ không phải đối thủ tranh giành nguồn lực.'),
('当然，代际合作不能只靠个人善意，还需要制度提供时间、场地和持续资金。','Tất nhiên, hợp tác liên thế hệ không thể chỉ dựa vào thiện chí cá nhân mà cần thể chế cung cấp thời gian, địa điểm và tài chính bền vững.'),
('面对老龄化，最危险的做法是把所有老人想象成同一种人，并把所有问题都推给家庭自己解决。','Trước già hóa, cách nguy hiểm nhất là tưởng mọi người già giống nhau và đẩy mọi vấn đề cho gia đình tự giải quyết.'),
('更成熟的社会会承认衰老是每个人生命过程的一部分，并提前建设能够支持不同阶段生活的环境。','Một xã hội trưởng thành hơn sẽ thừa nhận lão hóa là một phần đời mỗi người và sớm xây dựng môi trường hỗ trợ các giai đoạn sống khác nhau.'),
('当尊严、选择和相互支持成为制度目标时，人口结构变化也可以转化为重新设计社会的机会。','Khi phẩm giá, lựa chọn và hỗ trợ lẫn nhau trở thành mục tiêu thể chế, thay đổi cơ cấu dân số cũng có thể thành cơ hội thiết kế lại xã hội.'),
],1000),
('information-bubble','Thuật toán đề xuất và bong bóng thông tin','truyền thông',[
('每天打开手机，新闻、短视频和商品会自动出现在屏幕上，用户不需要主动搜索，就能得到大量似乎符合兴趣的内容。','Mỗi ngày mở điện thoại, tin tức, video ngắn và hàng hóa tự xuất hiện; người dùng không cần chủ động tìm vẫn nhận nhiều nội dung dường như hợp sở thích.'),
('这些推荐系统根据点击、停留时间、点赞和购买记录，预测人们下一步可能关注什么。','Các hệ thống đề xuất dựa vào lượt nhấp, thời gian xem, thích và lịch sử mua để dự đoán điều người dùng có thể quan tâm tiếp theo.'),
('从效率看，这种技术帮助我们在海量信息中节省时间，也让小众创作者有机会找到真正感兴趣的观众。','Về hiệu quả, công nghệ giúp tiết kiệm thời gian giữa biển thông tin và cho nhà sáng tạo ngách cơ hội tìm đúng khán giả.'),
('但是，当平台不断提供相似内容时，用户可能逐渐进入所谓的信息茧房。','Nhưng khi nền tảng liên tục cung cấp nội dung tương tự, người dùng có thể dần bước vào “kén thông tin”.'),
('在这个环境里，人们经常看到支持自己观点的材料，却很少接触不同立场和完整背景。','Trong môi trường này, người ta thường thấy tài liệu ủng hộ quan điểm mình nhưng ít tiếp xúc lập trường khác và bối cảnh đầy đủ.'),
('时间久了，熟悉的观点会被误认为普遍事实，而持不同意见的人则显得难以理解。','Lâu dần, quan điểm quen thuộc bị nhầm là sự thật phổ quát, còn người khác ý trở nên khó hiểu.'),
('推荐系统并不一定故意制造分裂，它的主要目标通常是延长使用时间和提高互动。','Hệ thống đề xuất không nhất thiết cố ý tạo chia rẽ; mục tiêu chính thường là kéo dài thời gian sử dụng và tăng tương tác.'),
('然而，愤怒、恐惧和冲突往往比平静、复杂的解释更容易吸引注意。','Tuy nhiên, giận dữ, sợ hãi và xung đột thường dễ thu hút chú ý hơn lời giải thích bình tĩnh, phức tạp.'),
('结果是，极端标题和情绪化内容可能获得更多传播，即使它们并不准确。','Kết quả là tiêu đề cực đoan và nội dung cảm tính có thể lan truyền nhiều hơn dù không chính xác.'),
('个人要避免完全被算法带着走，首先需要意识到推荐结果不是客观世界的缩小版，而是经过商业目标和个人记录筛选的页面。','Để tránh bị thuật toán dẫn dắt hoàn toàn, cá nhân trước hết cần hiểu kết quả đề xuất không phải bản thu nhỏ khách quan của thế giới mà là trang đã lọc qua mục tiêu thương mại và dữ liệu cá nhân.'),
('我们可以主动订阅不同来源，定期阅读与自己观点不完全一致的文章，并在转发前检查原始出处。','Ta có thể chủ động theo dõi nguồn khác nhau, định kỳ đọc bài không hoàn toàn cùng quan điểm và kiểm tra nguồn gốc trước khi chia sẻ.'),
('面对令人震惊的信息，暂时停止反应、寻找多个可靠来源，通常比立刻评论更有帮助。','Trước thông tin gây sốc, tạm dừng phản ứng và tìm nhiều nguồn đáng tin thường hữu ích hơn bình luận ngay.'),
('媒体教育也不应只教人识别假新闻，还要帮助公众理解平台如何排序内容、广告如何影响表达，以及数据如何被收集。','Giáo dục truyền thông không chỉ dạy nhận biết tin giả mà còn giúp công chúng hiểu nền tảng xếp nội dung thế nào, quảng cáo ảnh hưởng biểu đạt ra sao và dữ liệu được thu thập thế nào.'),
('平台方面则应提供更透明的说明，让用户知道为什么看到某条内容，并允许他们调整推荐规则。','Về phía nền tảng, cần giải thích minh bạch hơn vì sao người dùng thấy nội dung nào và cho phép điều chỉnh quy tắc đề xuất.'),
('对于涉及公共安全、选举和健康的信息，平台还需要承担更高的核查责任。','Với thông tin liên quan an toàn công cộng, bầu cử và sức khỏe, nền tảng còn cần trách nhiệm kiểm chứng cao hơn.'),
('但透明并不等于公开全部技术细节，因为系统复杂且不断变化。','Nhưng minh bạch không có nghĩa phải công khai mọi chi tiết kỹ thuật vì hệ thống phức tạp và thay đổi liên tục.'),
('更现实的做法是公布原则、风险和纠错机制，并接受独立研究者的审查。','Cách thực tế hơn là công bố nguyên tắc, rủi ro, cơ chế sửa lỗi và chấp nhận kiểm tra của nhà nghiên cứu độc lập.'),
('信息环境的健康也不能只依赖个人自律，因为人在疲劳、焦虑或时间不足时更容易选择简单答案。','Môi trường thông tin lành mạnh cũng không thể chỉ dựa vào tự giác cá nhân vì khi mệt, lo hoặc thiếu thời gian, con người dễ chọn đáp án đơn giản.'),
('因此，设计者、媒体、监管者和用户都应共同承担责任。','Vì vậy, nhà thiết kế, truyền thông, cơ quan quản lý và người dùng đều cần cùng chịu trách nhiệm.'),
('技术可以帮助我们发现兴趣，也可能限制我们理解世界的范围，关键在于是否保留主动选择和修正的空间。','Công nghệ có thể giúp ta khám phá sở thích nhưng cũng giới hạn phạm vi hiểu thế giới; điều cốt lõi là có giữ được không gian lựa chọn và sửa đổi chủ động hay không.'),
('真正的信息自由，不是屏幕上内容无限增加，而是人们有能力知道自己为何看到这些内容，并能走出熟悉的范围。','Tự do thông tin thật sự không phải nội dung trên màn hình tăng vô hạn mà là người dùng biết vì sao mình thấy chúng và có thể bước ra khỏi vùng quen thuộc.'),
],1000),
('craft','Nghề thủ công truyền thống trong đời sống hiện đại','văn hóa',[
('传统手工艺常被当作过去生活的象征，出现在博物馆、节庆和旅游纪念品中。','Nghề thủ công truyền thống thường được xem là biểu tượng của đời sống quá khứ, xuất hiện trong bảo tàng, lễ hội và quà lưu niệm.'),
('然而，对真正从事这类工作的人来说，它不仅是文化展示，也是需要面对材料成本、市场变化和收入压力的职业。','Nhưng với người thực sự làm nghề, đó không chỉ là trưng bày văn hóa mà còn là nghề phải đối mặt chi phí vật liệu, biến động thị trường và áp lực thu nhập.'),
('许多手艺需要多年训练，学习者必须反复观察、模仿和修正，才能掌握看似简单的动作。','Nhiều nghề cần nhiều năm đào tạo; người học phải quan sát, bắt chước và sửa đi sửa lại mới nắm được động tác tưởng đơn giản.'),
('当年轻人发现付出的时间很长、收入却不稳定时，他们往往选择到城市从事其他工作。','Khi người trẻ thấy thời gian bỏ ra dài mà thu nhập không ổn định, họ thường chọn lên thành phố làm nghề khác.'),
('如果传承只依靠个人牺牲，很多技艺就可能随着老艺人离开而中断。','Nếu truyền nghề chỉ dựa vào hy sinh cá nhân, nhiều kỹ thuật có thể đứt đoạn khi nghệ nhân lớn tuổi qua đời hoặc nghỉ nghề.'),
('保护手工艺首先要记录知识，包括工具使用、材料处理、图案含义和制作过程中的判断。','Bảo tồn nghề thủ công trước hết cần ghi chép kiến thức gồm cách dùng công cụ, xử lý vật liệu, ý nghĩa hoa văn và phán đoán trong quá trình làm.'),
('视频和数字档案可以保存细节，但它们不能完全代替师徒之间长期的现场学习。','Video và hồ sơ số có thể lưu chi tiết nhưng không thể thay thế hoàn toàn việc học trực tiếp lâu dài giữa thầy và trò.'),
('手的力度、材料的湿度和制作时机，往往很难只用文字说明。','Lực tay, độ ẩm vật liệu và thời điểm thao tác thường rất khó giải thích chỉ bằng chữ.'),
('因此，培训项目需要为学习者提供足够时间、基本收入和真正参与生产的机会。','Vì vậy, chương trình đào tạo cần cung cấp đủ thời gian, thu nhập cơ bản và cơ hội tham gia sản xuất thật.'),
('与此同时，传统也不是完全不能改变。','Đồng thời, truyền thống không có nghĩa là hoàn toàn không được thay đổi.'),
('如果产品只复制旧样式，却无法进入现代生活，市场就会越来越小。','Nếu sản phẩm chỉ sao chép mẫu cũ mà không đi vào đời sống hiện đại, thị trường sẽ ngày càng nhỏ.'),
('一些设计师与工匠合作，把传统技术用于灯具、家具、服装和公共空间，使材料和工艺获得新的用途。','Một số nhà thiết kế hợp tác với thợ thủ công, dùng kỹ thuật truyền thống vào đèn, nội thất, quần áo và không gian công cộng, tạo công dụng mới cho vật liệu và nghề.'),
('这种合作可以带来机会，也可能造成不平等。','Sự hợp tác này có thể tạo cơ hội nhưng cũng có thể gây bất bình đẳng.'),
('如果品牌只使用“传统”作为宣传，却不给工匠合理报酬或署名，文化就会变成被利用的装饰。','Nếu thương hiệu chỉ dùng “truyền thống” để quảng bá mà không trả công hợp lý hay ghi tên thợ, văn hóa sẽ thành vật trang trí bị lợi dụng.'),
('合作前应明确知识来源、利益分配和谁有权决定图案如何使用。','Trước hợp tác cần làm rõ nguồn tri thức, phân chia lợi ích và ai có quyền quyết định cách dùng hoa văn.'),
('地方政府和学校也可以通过公共采购、课程和展览建立稳定需求，而不是只在节日短暂关注。','Chính quyền địa phương và trường học có thể tạo nhu cầu ổn định qua mua sắm công, khóa học và triển lãm, thay vì chỉ chú ý ngắn hạn vào dịp lễ.'),
('消费者则可以了解产品背后的时间与技术，接受手工制品之间自然存在的差异。','Người tiêu dùng có thể tìm hiểu thời gian và kỹ thuật phía sau sản phẩm, chấp nhận khác biệt tự nhiên giữa đồ thủ công.'),
('手工艺的价值不一定在于每件作品都完美一致，而在于材料、劳动和地方经验留下了可以被看见的痕迹。','Giá trị nghề thủ công không nhất thiết ở việc mọi sản phẩm giống hệt hoàn hảo mà ở dấu vết có thể thấy của vật liệu, lao động và kinh nghiệm địa phương.'),
('真正的传承既不是把过去封闭起来，也不是为了市场随意改变一切。','Truyền thừa thật sự không phải đóng kín quá khứ cũng không phải tùy ý đổi mọi thứ vì thị trường.'),
('它需要在尊重核心知识的同时，允许新一代根据生活条件继续创造。','Nó cần tôn trọng tri thức cốt lõi đồng thời cho phép thế hệ mới tiếp tục sáng tạo theo điều kiện sống.'),
('只有当手艺人能够有尊严地生活，传统文化才不会停留在口号和展柜里。','Chỉ khi người làm nghề có thể sống có phẩm giá, văn hóa truyền thống mới không dừng ở khẩu hiệu và tủ trưng bày.'),
],1000),
]

HSK7 = [
('work-meaning','Tiến bộ công nghệ và ý nghĩa của lao động','công nghệ xã hội',[
('每一轮技术革命都会重新定义哪些工作值得由人完成，哪些任务可以交给机器，以及社会应如何分配由生产率提高所带来的收益。','Mỗi cuộc cách mạng công nghệ đều định nghĩa lại công việc nào đáng để con người làm, nhiệm vụ nào có thể giao cho máy và xã hội nên phân phối lợi ích từ năng suất tăng ra sao.'),
('从蒸汽机到自动化生产线，再到今天能够生成文字、图像和程序的人工智能，技术一直在减少某些劳动，同时创造新的职业与依赖。','Từ máy hơi nước, dây chuyền tự động đến AI tạo văn bản, hình ảnh và chương trình, công nghệ luôn làm giảm một số loại lao động đồng thời tạo nghề và sự phụ thuộc mới.'),
('公众讨论往往集中在“机器会不会抢走工作”，但这个问题过于简单，因为工作并不是固定数量的岗位，也不只是获得工资的手段。','Thảo luận công chúng thường tập trung vào “máy có cướp việc không”, nhưng câu hỏi này quá đơn giản vì việc làm không phải số vị trí cố định và cũng không chỉ là phương tiện nhận lương.'),
('劳动还提供日常结构、社会关系、身份认同和参与共同生活的方式。','Lao động còn cung cấp cấu trúc hằng ngày, quan hệ xã hội, bản sắc và cách tham gia đời sống chung.'),
('如果技术替代了重复、危险和损害健康的任务，它可以让人从不必要的消耗中解放出来。','Nếu công nghệ thay thế nhiệm vụ lặp lại, nguy hiểm và hại sức khỏe, nó có thể giải phóng con người khỏi hao mòn không cần thiết.'),
('然而，如果节省下来的时间只转化为裁员、收入下降和工作强度增加，那么生产率进步就不会自动带来更好的生活。','Nhưng nếu thời gian tiết kiệm chỉ chuyển thành sa thải, giảm thu nhập và cường độ cao hơn, tiến bộ năng suất sẽ không tự động mang lại cuộc sống tốt hơn.'),
('关键不在于技术本身是否先进，而在于所有权、谈判能力和制度如何决定收益流向。','Điểm mấu chốt không phải công nghệ tiên tiến đến đâu mà là quyền sở hữu, năng lực thương lượng và thể chế quyết định lợi ích chảy về đâu.'),
('当少数企业掌握数据、计算资源和市场入口时，劳动者可能更难分享自己帮助创造的价值。','Khi số ít doanh nghiệp nắm dữ liệu, tài nguyên tính toán và lối vào thị trường, người lao động có thể khó chia sẻ giá trị mình góp phần tạo ra.'),
('平台化工作就是一个例子：算法表面上提高了匹配效率，却也可能通过不透明评分、动态定价和随时变化的规则，把风险转移给个人。','Lao động nền tảng là một ví dụ: thuật toán bề ngoài tăng hiệu quả ghép nối nhưng có thể chuyển rủi ro sang cá nhân bằng chấm điểm mờ, định giá động và quy tắc thay đổi bất ngờ.'),
('在这种环境中，劳动者看似拥有自由时间，实际上却必须不断等待订单，并承担设备、保险和空闲时间的成本。','Trong môi trường ấy, người lao động có vẻ tự do thời gian nhưng thực tế phải liên tục chờ đơn và gánh chi phí thiết bị, bảo hiểm, thời gian trống.'),
('人工智能进入办公室以后，也可能改变专业工作的内部结构。','Khi AI vào văn phòng, nó cũng có thể thay đổi cấu trúc bên trong của lao động chuyên môn.'),
('初级人员过去通过整理资料、起草文件和检查细节来学习，现在这些任务若完全自动化，组织可能失去培养经验的阶梯。','Nhân sự mới trước đây học qua tổng hợp tài liệu, soạn thảo và kiểm tra chi tiết; nếu các việc này tự động hóa hoàn toàn, tổ chức có thể mất nấc thang đào tạo kinh nghiệm.'),
('短期效率因此可能与长期能力建设发生冲突。','Hiệu quả ngắn hạn vì thế có thể xung đột với xây dựng năng lực dài hạn.'),
('管理者若只计算完成一项任务所需的分钟数，就会忽略学习、判断和责任无法被简单压缩。','Nếu nhà quản lý chỉ tính số phút hoàn thành nhiệm vụ, họ sẽ bỏ qua việc học, phán đoán và trách nhiệm không thể nén đơn giản.'),
('另一个问题是，自动化系统常常把复杂决策拆成标准指标，而指标一旦成为考核目标，人们就会围绕指标行动。','Một vấn đề khác là hệ thống tự động thường chia quyết định phức tạp thành chỉ số chuẩn; khi chỉ số trở thành mục tiêu đánh giá, con người sẽ hành động xoay quanh chỉ số.'),
('医院可能追求处理数量而忽视交流质量，学校可能追求分数而减少探索，客服可能追求通话时长而不真正解决问题。','Bệnh viện có thể chạy theo số lượng xử lý mà bỏ chất lượng giao tiếp; trường chạy theo điểm mà giảm khám phá; chăm sóc khách hàng chạy theo thời lượng gọi mà không giải quyết thật sự.'),
('这并不说明数据无用，而是说明任何测量都只能代表现实的一部分。','Điều này không có nghĩa dữ liệu vô dụng mà cho thấy mọi đo lường chỉ đại diện một phần thực tế.'),
('保留人工判断，并让受影响的人能够质疑系统，是避免效率逻辑压倒公共价值的重要条件。','Giữ phán đoán của con người và cho người bị ảnh hưởng quyền chất vấn hệ thống là điều kiện quan trọng để logic hiệu quả không lấn át giá trị công.'),
('面对技术变化，教育政策通常强调“提高技能”，但把全部责任放在个人身上并不公平。','Trước thay đổi công nghệ, chính sách giáo dục thường nhấn mạnh “nâng kỹ năng”, nhưng đặt toàn bộ trách nhiệm lên cá nhân là không công bằng.'),
('一个中年劳动者即使愿意学习，也可能缺少时间、资金和明确的就业机会。','Một lao động trung niên dù muốn học vẫn có thể thiếu thời gian, tiền và cơ hội việc làm rõ ràng.'),
('有效的转型需要企业承担培训义务，公共机构提供收入支持，并让职业教育与真实岗位需求相连接。','Chuyển đổi hiệu quả cần doanh nghiệp chịu nghĩa vụ đào tạo, cơ quan công hỗ trợ thu nhập và giáo dục nghề gắn với nhu cầu việc làm thật.'),
('同时，社会还应重新评价照护、教育、维护环境和社区服务等难以完全自动化的劳动。','Đồng thời, xã hội cần đánh giá lại lao động chăm sóc, giáo dục, bảo trì môi trường và dịch vụ cộng đồng vốn khó tự động hóa hoàn toàn.'),
('这些工作常常创造巨大的社会价值，却因为无法快速扩大规模或产生直接利润而被低估。','Những công việc này thường tạo giá trị xã hội lớn nhưng bị đánh giá thấp vì không thể mở rộng nhanh hoặc sinh lợi trực tiếp.'),
('如果技术让商品生产更便宜，却没有改善照护者、教师和基础服务人员的待遇，所谓进步就仍然是不完整的。','Nếu công nghệ làm hàng hóa rẻ hơn nhưng không cải thiện đãi ngộ người chăm sóc, giáo viên và nhân viên dịch vụ thiết yếu, tiến bộ vẫn chưa đầy đủ.'),
('缩短工作时间是另一种可能的制度回应。','Rút ngắn thời gian làm việc là một phản ứng thể chế khả thi khác.'),
('当生产率提高时，社会可以选择把一部分收益转化为更多休息、学习和家庭时间，而不是只追求产量继续增长。','Khi năng suất tăng, xã hội có thể chuyển một phần lợi ích thành thêm thời gian nghỉ, học và gia đình thay vì chỉ tiếp tục tăng sản lượng.'),
('这需要改变把长时间工作等同于勤奋的文化，也需要保证低收入者不会因为减少工时而失去基本生活保障。','Điều này cần thay đổi văn hóa đồng nhất làm lâu với chăm chỉ, đồng thời bảo đảm người thu nhập thấp không mất sinh kế cơ bản khi giảm giờ.'),
('有些人提出基本收入，以便在岗位快速变化时提供安全网；另一些人担心它会削弱公共服务或掩盖不平等的劳动关系。','Một số người đề xuất thu nhập cơ bản để tạo lưới an toàn khi việc làm đổi nhanh; người khác lo nó làm yếu dịch vụ công hoặc che giấu quan hệ lao động bất bình đẳng.'),
('这些方案没有简单答案，但共同指出一个事实：技术造成的风险不能只由最脆弱的人承担。','Các phương án không có đáp án đơn giản nhưng cùng chỉ ra rằng rủi ro do công nghệ tạo ra không thể chỉ do người yếu thế nhất gánh.'),
('此外，我们还需要警惕把所有人的价值都与市场就业绑定。','Ngoài ra, cần cảnh giác việc buộc giá trị của mọi người vào việc làm thị trường.'),
('照顾家人、参与社区、创作、学习和休息，都是有意义的人类活动，即使它们没有工资。','Chăm sóc gia đình, tham gia cộng đồng, sáng tạo, học và nghỉ đều là hoạt động có ý nghĩa dù không có lương.'),
('当自动化减少必要劳动时，真正值得追问的不是如何制造更多忙碌，而是如何让人拥有选择有意义活动的条件。','Khi tự động hóa giảm lao động cần thiết, câu hỏi đáng hỏi không phải làm sao tạo thêm bận rộn mà là làm sao để con người có điều kiện lựa chọn hoạt động có ý nghĩa.'),
('这要求社会同时讨论收入分配、公共服务、时间权利和民主参与，而不能把未来交给技术企业单独决定。','Điều này đòi hỏi xã hội cùng bàn về phân phối thu nhập, dịch vụ công, quyền về thời gian và tham gia dân chủ, không thể để doanh nghiệp công nghệ đơn độc quyết định tương lai.'),
('技术确实会改变工作，但工作的未来从来不是技术预测的自然结果，而是政治选择、社会谈判和日常实践共同形成的。','Công nghệ đúng là sẽ thay đổi việc làm, nhưng tương lai lao động chưa bao giờ là kết quả tự nhiên của dự báo kỹ thuật mà do lựa chọn chính trị, thương lượng xã hội và thực hành hằng ngày cùng tạo nên.'),
('如果进步能够减少痛苦、扩大自主并让更多人分享安全与尊严，它才不仅是机器能力的增长，也是社会能力的增长。','Nếu tiến bộ giảm đau khổ, mở rộng tự chủ và giúp nhiều người cùng chia sẻ an toàn và phẩm giá, nó mới không chỉ là tăng năng lực máy mà còn là tăng năng lực xã hội.'),
],1500),
('climate-fairness','Công bằng trong quản trị khí hậu','môi trường chính sách',[
('气候变化是一个全球问题，但它造成的影响与应对成本并不会平均分配。','Biến đổi khí hậu là vấn đề toàn cầu nhưng tác động và chi phí ứng phó không được phân bổ đồng đều.'),
('历史上排放较多的国家积累了财富和基础设施，而许多排放较少的地区却更容易遭受高温、洪水、干旱和海平面上升。','Các nước phát thải nhiều trong lịch sử tích lũy của cải và hạ tầng, trong khi nhiều vùng phát thải ít lại dễ chịu nóng cực đoan, lũ, hạn và nước biển dâng.'),
('同一个城市内部也存在类似差异：富裕社区通常拥有更多树木、较好的住房和保险，低收入居民则可能住在热岛、污染源或容易积水的地区。','Trong cùng thành phố cũng có khác biệt: khu giàu thường nhiều cây, nhà tốt và có bảo hiểm; người thu nhập thấp có thể sống ở đảo nhiệt, gần nguồn ô nhiễm hoặc nơi dễ ngập.'),
('因此，气候政策不仅是减少多少吨排放的问题，也是由谁决定、谁付费、谁得到保护的问题。','Vì vậy, chính sách khí hậu không chỉ là giảm bao nhiêu tấn phát thải mà còn là ai quyết định, ai trả và ai được bảo vệ.'),
('碳税被认为能够通过价格信号减少化石能源使用，但如果没有配套措施，它可能使能源费用在低收入家庭预算中占据更高比例。','Thuế carbon được cho là giảm dùng nhiên liệu hóa thạch qua tín hiệu giá, nhưng nếu không có hỗ trợ, chi phí năng lượng có thể chiếm tỷ trọng cao hơn trong ngân sách hộ thu nhập thấp.'),
('公平的设计可以把税收返还给居民，补贴节能改造和公共交通，并优先帮助最难承担成本的人。','Thiết kế công bằng có thể hoàn trả thuế cho dân, trợ cấp cải tạo tiết kiệm năng lượng và giao thông công cộng, ưu tiên người khó gánh chi phí nhất.'),
('能源转型还会改变就业。','Chuyển đổi năng lượng còn làm thay đổi việc làm.'),
('关闭煤矿和高污染工厂有利于环境与健康，却可能使依赖单一产业的地区失去收入来源。','Đóng mỏ than và nhà máy ô nhiễm có lợi cho môi trường, sức khỏe nhưng có thể khiến vùng phụ thuộc một ngành mất nguồn thu.'),
('所谓“公正转型”要求提前规划培训、社会保障和新的投资，而不是在企业关闭以后才让工人自己寻找出路。','“Chuyển đổi công bằng” đòi hỏi lên kế hoạch trước về đào tạo, an sinh và đầu tư mới, không phải để công nhân tự xoay xở sau khi doanh nghiệp đóng cửa.'),
('新产业提供的岗位是否稳定、工资是否合理、是否位于原有社区，也同样重要。','Việc làm ngành mới có ổn định, lương hợp lý và nằm tại cộng đồng cũ hay không cũng quan trọng.'),
('在国际层面，发展中国家常指出，它们仍需要改善住房、交通和能源服务，不能简单复制富裕国家过去高排放的发展道路。','Ở cấp quốc tế, các nước đang phát triển thường nói họ vẫn cần cải thiện nhà ở, giao thông và năng lượng, không thể đơn giản lặp lại con đường phát thải cao của nước giàu.'),
('富裕国家若只要求他国迅速减排，却不提供资金、技术和政策空间，就很难建立长期信任。','Nếu nước giàu chỉ yêu cầu nước khác giảm nhanh mà không cung cấp tài chính, công nghệ và không gian chính sách, rất khó xây dựng niềm tin lâu dài.'),
('气候融资因此不应只是贷款，因为让受灾国家为并非主要由它们造成的问题承担更多债务，本身就可能加深不平等。','Tài chính khí hậu vì thế không nên chỉ là khoản vay, vì buộc nước chịu thiên tai gánh thêm nợ cho vấn đề không chủ yếu do họ gây ra có thể làm bất bình đẳng sâu hơn.'),
('赠款、技术共享和损失损害资金，是承认历史责任的不同方式。','Viện trợ không hoàn lại, chia sẻ công nghệ và quỹ tổn thất thiệt hại là những cách khác nhau để thừa nhận trách nhiệm lịch sử.'),
('适应政策同样需要公平视角。','Chính sách thích ứng cũng cần góc nhìn công bằng.'),
('修建海堤可以保护中心城区，却可能把洪水风险转移到邻近地区；扩大水库能保障城市供水，却可能影响上游社区和生态系统。','Xây đê biển có thể bảo vệ trung tâm nhưng chuyển rủi ro lũ sang vùng lân cận; mở rộng hồ chứa bảo đảm nước đô thị nhưng có thể ảnh hưởng cộng đồng thượng nguồn và hệ sinh thái.'),
('如果只根据经济资产价值排序，贫困社区往往会被认为“不值得优先保护”。','Nếu chỉ xếp ưu tiên theo giá trị tài sản kinh tế, cộng đồng nghèo thường bị coi là “không đáng bảo vệ trước”.'),
('更合理的评估应考虑生命安全、文化意义、社会联系和恢复能力。','Đánh giá hợp lý hơn cần tính đến an toàn tính mạng, ý nghĩa văn hóa, liên kết xã hội và khả năng phục hồi.'),
('原住民和地方社区拥有长期观察土地、水源和季节变化的知识，但他们的意见常在大型项目中被忽视。','Cộng đồng bản địa và địa phương có tri thức quan sát đất, nước và mùa qua thời gian dài nhưng ý kiến thường bị bỏ qua trong dự án lớn.'),
('真正的参与不是在方案完成后举行一次说明会，而是让受影响者从问题定义、方案选择到监督执行都拥有实质权力。','Tham gia thật sự không phải họp giải thích một lần sau khi phương án xong, mà là để người bị ảnh hưởng có quyền thực chất từ xác định vấn đề, chọn phương án đến giám sát thực hiện.'),
('个人消费当然会影响排放，但把气候责任主要归结为少开车、少用塑料或选择某种商品，会掩盖能源系统、城市规划和企业投资的结构性作用。','Tiêu dùng cá nhân có ảnh hưởng phát thải, nhưng quy trách nhiệm chủ yếu cho việc lái xe ít, dùng ít nhựa hay chọn sản phẩm sẽ che vai trò cấu trúc của hệ thống năng lượng, quy hoạch đô thị và đầu tư doanh nghiệp.'),
('很多人想选择低碳生活，却住在没有公共交通的地区，或者租住无法自行改造的房屋。','Nhiều người muốn sống carbon thấp nhưng ở nơi không có giao thông công cộng hoặc thuê nhà không thể tự cải tạo.'),
('政策应扩大实际可选项，而不是在选择不存在时责备个人。','Chính sách cần mở rộng lựa chọn thực tế thay vì trách cá nhân khi lựa chọn không tồn tại.'),
('企业的气候承诺也需要可核查的标准。','Cam kết khí hậu của doanh nghiệp cũng cần tiêu chuẩn có thể kiểm chứng.'),
('如果一家公司依靠购买质量不明的碳抵消，却继续扩大化石能源使用，它的“净零”目标可能只是延迟真正减排。','Nếu công ty dựa vào mua bù trừ carbon chất lượng không rõ trong khi tiếp tục mở rộng nhiên liệu hóa thạch, mục tiêu “net zero” có thể chỉ trì hoãn giảm phát thải thật.'),
('公开完整排放、供应链影响和投资计划，能够减少绿色宣传与实际行动之间的差距。','Công khai đầy đủ phát thải, tác động chuỗi cung ứng và kế hoạch đầu tư có thể giảm khoảng cách giữa quảng bá xanh và hành động thật.'),
('气候决策还必须面对不确定性。','Quyết định khí hậu còn phải đối mặt bất định.'),
('科学无法精确预测每个地区在每一年会发生什么，但不确定并不意味着可以等待所有细节确定后再行动。','Khoa học không thể dự đoán chính xác mọi vùng từng năm, nhưng bất định không có nghĩa có thể chờ mọi chi tiết rõ rồi mới hành động.'),
('当潜在损失巨大且难以逆转时，预防原则要求提前降低风险，同时根据新证据不断调整。','Khi tổn thất tiềm ẩn lớn và khó đảo ngược, nguyên tắc phòng ngừa yêu cầu giảm rủi ro sớm và liên tục điều chỉnh theo bằng chứng mới.'),
('公平也包含代际维度，因为今天的基础设施和排放会影响尚未参与决策的人。','Công bằng còn có chiều kích liên thế hệ vì hạ tầng và phát thải hôm nay ảnh hưởng người chưa tham gia quyết định.'),
('然而，不能为了抽象的未来利益而牺牲当下最贫困者的基本需求。','Tuy nhiên, không thể vì lợi ích tương lai trừu tượng mà hy sinh nhu cầu cơ bản của người nghèo nhất hiện tại.'),
('真正公正的政策应同时减少长期风险与当前不平等，使清洁空气、可靠能源和安全住房成为共同收益。','Chính sách thực sự công bằng cần đồng thời giảm rủi ro dài hạn và bất bình đẳng hiện tại, biến không khí sạch, năng lượng đáng tin và nhà an toàn thành lợi ích chung.'),
('气候治理之所以困难，不是因为公平会妨碍效率，而是因为忽视公平的政策通常缺少社会支持，最终也难以持续。','Quản trị khí hậu khó không phải vì công bằng cản hiệu quả, mà vì chính sách bỏ qua công bằng thường thiếu ủng hộ xã hội và khó bền vững.'),
('只有当人们相信成本与收益分配合理，并能参与影响自身生活的决定时，深刻转型才可能获得合法性。','Chỉ khi mọi người tin chi phí và lợi ích được phân bổ hợp lý và có thể tham gia quyết định ảnh hưởng đời sống, chuyển đổi sâu mới có tính chính danh.'),
('因此，气候行动不仅是技术工程，也是重新讨论责任、权力与共同未来的社会工程。','Vì vậy, hành động khí hậu không chỉ là công trình kỹ thuật mà còn là công trình xã hội bàn lại trách nhiệm, quyền lực và tương lai chung.'),
],1500),
('public-memory','Ký ức công cộng, lịch sử và trách nhiệm','lịch sử văn hóa',[
('社会如何记住过去，并不是一个只属于历史学家的问题。','Xã hội nhớ quá khứ thế nào không phải vấn đề chỉ thuộc về sử gia.'),
('纪念碑、博物馆、教科书、地名、电影和家庭故事，都在决定哪些经验被看见，哪些声音被遗忘，以及今天的人如何理解自己的位置。','Tượng đài, bảo tàng, sách giáo khoa, địa danh, phim và chuyện gia đình đều quyết định kinh nghiệm nào được thấy, tiếng nói nào bị quên và con người hôm nay hiểu vị trí mình ra sao.'),
('公共记忆看似在保存事实，实际上也包含选择、解释和权力。','Ký ức công cộng có vẻ lưu giữ sự thật nhưng thực tế còn chứa lựa chọn, diễn giải và quyền lực.'),
('任何展览都必须从大量材料中选择有限内容，任何纪念仪式也会通过时间、地点和语言强调某种意义。','Mọi triển lãm phải chọn nội dung hữu hạn từ lượng tư liệu lớn; mọi nghi lễ tưởng niệm cũng nhấn mạnh ý nghĩa qua thời gian, địa điểm và ngôn ngữ.'),
('选择本身不可避免，问题在于选择过程是否透明，是否允许被排除的人提出质疑。','Lựa chọn là không tránh khỏi; vấn đề là quá trình có minh bạch và cho người bị loại trừ quyền chất vấn hay không.'),
('胜利者、国家机构和社会精英通常拥有更多资源建立纪念物，因此官方叙事容易集中于英雄、战争和重大政治事件。','Bên chiến thắng, cơ quan nhà nước và giới tinh hoa thường có nhiều nguồn lực dựng công trình tưởng niệm, nên tự sự chính thức dễ tập trung vào anh hùng, chiến tranh và sự kiện chính trị lớn.'),
('普通人的劳动、迁移、照护经验以及少数群体遭受的损失，则可能缺少记录。','Lao động, di cư, kinh nghiệm chăm sóc của người thường và mất mát của nhóm thiểu số có thể ít được ghi chép.'),
('近年来，口述历史和社区档案尝试补充这些空白，让没有留下正式文件的人也能讲述自己的经历。','Những năm gần đây, lịch sử truyền miệng và kho lưu trữ cộng đồng cố bổ sung khoảng trống, để người không để lại tài liệu chính thức cũng kể trải nghiệm.'),
('口述材料非常珍贵，但记忆会受到时间、情感和后来知识的影响，因此不能被简单当作完全准确的录像。','Tư liệu truyền miệng rất quý nhưng ký ức chịu ảnh hưởng của thời gian, cảm xúc và hiểu biết sau này nên không thể coi như bản ghi hoàn toàn chính xác.'),
('历史研究需要把个人叙述与其他来源相互比较，同时尊重讲述者对创伤和隐私的边界。','Nghiên cứu lịch sử cần so sánh lời kể cá nhân với nguồn khác đồng thời tôn trọng ranh giới tổn thương và riêng tư của người kể.'),
('当社会面对暴力、压迫或制度性不公的历史时，纪念常常伴随争议。','Khi xã hội đối diện lịch sử bạo lực, áp bức hoặc bất công thể chế, tưởng niệm thường đi cùng tranh cãi.'),
('有人担心重新讨论会撕裂社会，希望尽快“向前看”；另一些人认为，没有承认事实和责任，就不可能建立真正的和解。','Có người lo thảo luận lại sẽ chia rẽ và muốn nhanh chóng “nhìn về phía trước”; người khác cho rằng nếu không thừa nhận sự thật và trách nhiệm thì không thể hòa giải thật.'),
('这两种立场之间的冲突说明，遗忘并不等于问题消失。','Xung đột giữa hai lập trường cho thấy lãng quên không đồng nghĩa vấn đề biến mất.'),
('被压抑的记忆可能继续影响家庭关系、土地争议、社会信任和不同群体对国家的态度。','Ký ức bị dồn nén có thể tiếp tục ảnh hưởng quan hệ gia đình, tranh chấp đất, niềm tin xã hội và thái độ các nhóm với nhà nước.'),
('道歉、赔偿、司法调查和纪念设施是处理历史伤害的不同工具，但没有一种措施能够单独完成修复。','Xin lỗi, bồi thường, điều tra tư pháp và công trình tưởng niệm là các công cụ khác nhau để xử lý tổn thương lịch sử, nhưng không biện pháp nào tự mình hoàn tất sửa chữa.'),
('形式化道歉如果没有制度改变，容易被视为空洞；经济赔偿如果忽视尊严和真相，也可能无法回应受害者的核心需要。','Lời xin lỗi hình thức không kèm thay đổi thể chế dễ bị xem là rỗng; bồi thường kinh tế nếu bỏ qua phẩm giá và sự thật cũng có thể không đáp ứng nhu cầu cốt lõi của nạn nhân.'),
('公共空间中的争议雕像尤其能体现记忆政治。','Tượng gây tranh cãi trong không gian công cộng thể hiện rõ chính trị ký ức.'),
('支持保留的人可能认为拆除等于删除历史，反对者则指出，雕像不是中立资料，而是在公共场所持续表达尊敬。','Người ủng hộ giữ lại có thể cho rằng dỡ bỏ là xóa lịch sử; người phản đối chỉ ra tượng không phải tư liệu trung lập mà liên tục biểu đạt sự tôn vinh ở nơi công cộng.'),
('解决办法并不只有保留或拆除两种。','Giải pháp không chỉ có giữ hoặc dỡ.'),
('移动到博物馆、增加背景说明、设置反向纪念物或重新设计空间，都可能使公众看到争议本身。','Chuyển vào bảo tàng, thêm thuyết minh bối cảnh, dựng công trình đối thoại hoặc thiết kế lại không gian đều có thể giúp công chúng thấy chính tranh cãi.'),
('重要的是，不要把历史人物从时代背景中完全抽离，也不要用“时代不同”来免除一切责任。','Điều quan trọng là không tách nhân vật lịch sử hoàn toàn khỏi bối cảnh thời đại, cũng không dùng “thời khác” để miễn mọi trách nhiệm.'),
('历史理解需要同时承认结构限制和个人选择。','Hiểu lịch sử cần đồng thời thừa nhận giới hạn cấu trúc và lựa chọn cá nhân.'),
('教育在公共记忆中具有特殊作用。','Giáo dục có vai trò đặc biệt trong ký ức công cộng.'),
('如果教科书只提供唯一结论，学生可能记住事件，却没有学会如何分析证据和面对相互冲突的解释。','Nếu sách giáo khoa chỉ cho một kết luận, học sinh có thể nhớ sự kiện nhưng không học cách phân tích bằng chứng và đối diện diễn giải xung đột.'),
('更成熟的历史教育会展示来源如何形成、哪些材料缺失，以及为什么研究者会得出不同判断。','Giáo dục lịch sử trưởng thành hơn sẽ cho thấy nguồn hình thành thế nào, tư liệu nào thiếu và vì sao nhà nghiên cứu có phán đoán khác nhau.'),
('这并不是说所有观点都同样可靠。','Điều này không có nghĩa mọi quan điểm đều đáng tin như nhau.'),
('否认有充分证据支持的暴力事实，不能被包装成普通意见；开放讨论仍然需要证据标准。','Phủ nhận sự kiện bạo lực có bằng chứng đầy đủ không thể được bọc thành ý kiến thông thường; thảo luận mở vẫn cần tiêu chuẩn bằng chứng.'),
('数字技术为保存记忆提供了新机会，也带来新风险。','Công nghệ số mở ra cơ hội lưu giữ ký ức nhưng cũng tạo rủi ro mới.'),
('大量照片、视频和私人记录可以被保存与搜索，但平台关闭、格式过时和数据所有权问题也可能造成新的遗失。','Lượng lớn ảnh, video và ghi chép riêng có thể được lưu và tìm kiếm, nhưng nền tảng đóng cửa, định dạng lỗi thời và quyền sở hữu dữ liệu cũng có thể gây mất mát mới.'),
('人工智能能够修复影像、生成声音，却也可能制造看似真实的伪造材料，使未来研究者更难判断来源。','AI có thể phục hồi hình ảnh, tạo giọng nói nhưng cũng có thể tạo tư liệu giả trông thật, khiến nhà nghiên cứu tương lai khó đánh giá nguồn.'),
('因此，数字档案必须保留元数据、修改记录和可验证的来源链。','Vì vậy, kho lưu trữ số phải giữ siêu dữ liệu, lịch sử chỉnh sửa và chuỗi nguồn có thể xác minh.'),
('个人和家庭在决定公开资料时，还需要考虑逝者尊严、后代隐私和社区文化规范。','Cá nhân và gia đình khi công khai tư liệu còn cần cân nhắc phẩm giá người đã mất, riêng tư hậu thế và chuẩn mực văn hóa cộng đồng.'),
('公共记忆的目标不应是建立一个永远不变的统一故事。','Mục tiêu ký ức công cộng không nên là tạo một câu chuyện thống nhất bất biến.'),
('一个民主社会更需要的是能够持续修正叙事、承认新证据，并让不同群体在共同空间中表达经验的机制。','Một xã hội dân chủ cần cơ chế liên tục sửa tự sự, thừa nhận bằng chứng mới và cho các nhóm biểu đạt trải nghiệm trong không gian chung.'),
('记住过去也不是为了让后代继承仇恨，而是为了理解制度如何造成伤害，以及今天有哪些责任可以避免重复。','Nhớ quá khứ không nhằm để hậu thế kế thừa thù hận mà để hiểu thể chế gây tổn thương thế nào và hôm nay có trách nhiệm gì để tránh lặp lại.'),
('当纪念能够连接事实、同情与行动时，历史才不只是过去的负担，也会成为建设更公正未来的资源。','Khi tưởng niệm kết nối sự thật, đồng cảm và hành động, lịch sử không chỉ là gánh nặng quá khứ mà còn là nguồn lực xây tương lai công bằng hơn.'),
],1500),
('science-uncertainty','Bất định khoa học và quyết định công','khoa học chính sách',[
('公众常希望科学能够给出明确答案：某种物质是否安全，一项政策是否有效，一种疾病会如何传播。','Công chúng thường muốn khoa học cho đáp án rõ: một chất có an toàn không, chính sách có hiệu quả không, bệnh sẽ lây ra sao.'),
('然而，科学知识通常不是一次完成的结论，而是在证据积累、方法改进和同行批评中不断变化的判断。','Nhưng tri thức khoa học thường không phải kết luận hoàn tất một lần mà là phán đoán thay đổi qua tích lũy bằng chứng, cải tiến phương pháp và phê bình đồng nghiệp.'),
('不确定性因此不是科学失败的标志，而是对证据边界的诚实描述。','Bất định vì thế không phải dấu hiệu khoa học thất bại mà là mô tả trung thực về ranh giới bằng chứng.'),
('问题在于，公共决策往往不能等待所有疑问消失。','Vấn đề là quyết định công thường không thể chờ mọi nghi vấn biến mất.'),
('面对传染病、环境污染或新技术风险，政府必须在信息不完整时采取行动，并承担行动过早或过晚的后果。','Trước dịch bệnh, ô nhiễm môi trường hay rủi ro công nghệ mới, chính phủ phải hành động khi thông tin chưa đầy đủ và chịu hậu quả của hành động quá sớm hoặc quá muộn.'),
('这要求区分不同类型的不确定性。','Điều này đòi hỏi phân biệt các loại bất định.'),
('有时数据不足，但可以通过更多测量降低不确定；有时模型对复杂系统作出不同预测；还有些风险来自人类行为，本身会随着政策和信息改变。','Đôi khi thiếu dữ liệu nhưng có thể giảm bất định bằng đo thêm; đôi khi mô hình dự báo khác nhau về hệ phức tạp; có rủi ro đến từ hành vi con người và thay đổi theo chính sách, thông tin.'),
('把所有不确定性用一个百分比表示，可能掩盖这些差别。','Biểu diễn mọi bất định bằng một tỷ lệ có thể che lấp khác biệt đó.'),
('科学顾问需要说明哪些事实较稳定、哪些结论依赖假设，以及什么新证据会改变建议。','Cố vấn khoa học cần nói rõ sự kiện nào khá ổn định, kết luận nào phụ thuộc giả định và bằng chứng mới nào sẽ làm thay đổi khuyến nghị.'),
('这种透明表达有时会被误解为专家没有把握。','Cách diễn đạt minh bạch đôi khi bị hiểu lầm là chuyên gia thiếu chắc chắn.'),
('政治传播则倾向于简单口号，因为复杂说明难以在短时间内吸引注意。','Truyền thông chính trị lại thiên về khẩu hiệu đơn giản vì giải thích phức tạp khó thu hút chú ý trong thời gian ngắn.'),
('如果官员为了显示权威而隐藏不确定性，当建议后来调整时，公众可能认为之前的说法都是欺骗。','Nếu quan chức giấu bất định để tỏ ra có quyền uy, khi khuyến nghị sau đó điều chỉnh, công chúng có thể cho rằng lời trước đều là lừa dối.'),
('相反，提前说明“我们目前知道什么、还不知道什么、下一步如何学习”，更有助于建立可持续信任。','Ngược lại, nói trước “hiện biết gì, chưa biết gì, bước tiếp theo học thế nào” giúp xây niềm tin bền vững hơn.'),
('风险沟通还必须区分相对风险和绝对风险。','Truyền thông rủi ro còn phải phân biệt rủi ro tương đối và tuyệt đối.'),
('一种干预把风险降低一半听起来非常显著，但如果原始风险是万分之二，实际变化可能只是降到万分之一。','Một can thiệp giảm rủi ro một nửa nghe rất lớn, nhưng nếu rủi ro gốc là hai trên mười nghìn thì thay đổi thực tế chỉ còn một trên mười nghìn.'),
('同样，只报道单个严重案例会放大恐惧，却不能说明总体发生概率。','Tương tự, chỉ đưa tin một ca nghiêm trọng làm tăng sợ hãi nhưng không cho biết xác suất chung.'),
('媒体和机构应提供可比较的数字、时间范围和受影响人群，而不是只选择最戏剧化的表达。','Truyền thông và cơ quan nên cung cấp số liệu có thể so sánh, phạm vi thời gian và nhóm bị ảnh hưởng thay vì chỉ chọn cách diễn đạt kịch tính.'),
('预防原则常用于处理潜在损害巨大、不可逆转而证据尚不完整的风险。','Nguyên tắc phòng ngừa thường dùng cho rủi ro có tổn hại tiềm ẩn lớn, không thể đảo ngược trong khi bằng chứng chưa đầy đủ.'),
('它并不意味着只要存在任何怀疑就全面禁止，因为过度限制本身也会产生健康、经济和自由方面的成本。','Nó không có nghĩa hễ có nghi ngờ là cấm toàn diện, vì hạn chế quá mức cũng tạo chi phí về sức khỏe, kinh tế và tự do.'),
('合理应用需要比较不同选择的潜在损害，考虑可逆性，并设计能够随着证据更新的措施。','Áp dụng hợp lý cần so sánh tổn hại tiềm ẩn của các lựa chọn, xét khả năng đảo ngược và thiết kế biện pháp cập nhật theo bằng chứng.'),
('例如，可以先限制高风险用途、加强监测和要求报告，而不是立即在所有场景采取同样规则。','Ví dụ có thể trước hết hạn chế mục đích rủi ro cao, tăng giám sát và yêu cầu báo cáo thay vì áp một quy tắc cho mọi bối cảnh.'),
('公共决策还包含价值判断，这是科学数据无法单独决定的。','Quyết định công còn chứa phán đoán giá trị mà dữ liệu khoa học không thể tự quyết định.'),
('即使专家能够估计政策的成本和收益，社会仍需决定如何看待公平、隐私、个人选择和对弱势群体的责任。','Dù chuyên gia ước tính được chi phí và lợi ích, xã hội vẫn phải quyết định nhìn nhận công bằng, riêng tư, lựa chọn cá nhân và trách nhiệm với nhóm yếu thế ra sao.'),
('把价值选择包装成“科学要求”，会隐藏政治责任；反过来，否认事实并声称一切只是价值，则会破坏理性讨论。','Đóng gói lựa chọn giá trị thành “khoa học yêu cầu” sẽ che trách nhiệm chính trị; ngược lại, phủ nhận sự kiện và nói mọi thứ chỉ là giá trị sẽ phá hỏng thảo luận lý tính.'),
('更好的制度应明确区分证据分析、伦理权衡和最终决策，并记录每一步的理由。','Thể chế tốt hơn cần phân biệt rõ phân tích bằng chứng, cân nhắc đạo đức và quyết định cuối cùng, đồng thời ghi lại lý do từng bước.'),
('独立审查和公开数据能够减少利益冲突。','Thẩm định độc lập và dữ liệu mở có thể giảm xung đột lợi ích.'),
('研究由谁资助、负面结果是否发表、模型参数是否可以检查，都会影响结论的可信度。','Nghiên cứu do ai tài trợ, kết quả tiêu cực có được công bố, tham số mô hình có thể kiểm tra hay không đều ảnh hưởng độ tin cậy kết luận.'),
('但开放数据也要保护个人隐私，尤其在医疗、教育和社会福利领域。','Nhưng dữ liệu mở cũng phải bảo vệ riêng tư cá nhân, nhất là trong y tế, giáo dục và phúc lợi xã hội.'),
('这再次说明，透明不是简单地把所有资料上传，而是建立可追踪、可质疑且有边界的制度。','Điều này một lần nữa cho thấy minh bạch không phải tải mọi tài liệu lên mà là xây hệ thống có thể truy vết, chất vấn và có ranh giới.'),
('公众参与可以改善决策，因为当地居民往往知道模型没有包含的实际条件。','Sự tham gia của công chúng có thể cải thiện quyết định vì cư dân địa phương thường biết điều kiện thực tế mà mô hình không chứa.'),
('然而，参与也需要足够时间、易懂信息和回应机制，否则听证会只会成为形式。','Nhưng tham gia cần đủ thời gian, thông tin dễ hiểu và cơ chế phản hồi, nếu không điều trần chỉ là hình thức.'),
('在危机中，政策必须迅速，但快速行动不应取消事后评估。','Trong khủng hoảng, chính sách phải nhanh nhưng hành động nhanh không nên loại bỏ đánh giá sau đó.'),
('临时措施应设定期限、复审条件和退出机制，以免在风险下降后仍然永久存在。','Biện pháp tạm thời nên có thời hạn, điều kiện xem xét lại và cơ chế chấm dứt để không tồn tại vĩnh viễn sau khi rủi ro giảm.'),
('学习型治理的核心，是承认错误可能发生，并让制度能够发现、纠正和补偿错误。','Cốt lõi của quản trị học hỏi là thừa nhận lỗi có thể xảy ra và để thể chế phát hiện, sửa và bồi thường lỗi.'),
('一个从不修改政策的政府未必更可靠，可能只是拒绝承认新证据。','Một chính phủ không bao giờ sửa chính sách chưa chắc đáng tin hơn, có thể chỉ là từ chối thừa nhận bằng chứng mới.'),
('科学不确定性真正考验的不是我们能否消除所有疑问，而是能否在有限知识下作出负责、可修正并可解释的选择。','Bất định khoa học thực sự thử thách không phải khả năng xóa mọi nghi vấn, mà là có thể đưa ra lựa chọn có trách nhiệm, sửa được và giải thích được dưới tri thức hữu hạn hay không.'),
],1500),
('urban-resilience','Khả năng chống chịu đô thị trong hệ thống phức tạp','đô thị hệ thống',[
('城市通常被描述成建筑、道路和人口的集合，但从系统角度看，它更像由能源、水、交通、通信、医疗、市场和社会关系相互连接的网络。','Thành phố thường được mô tả là tập hợp công trình, đường sá và dân số, nhưng từ góc hệ thống, nó giống mạng lưới liên kết năng lượng, nước, giao thông, thông tin, y tế, thị trường và quan hệ xã hội.'),
('这些网络在日常生活中高度依赖彼此，因此一个局部故障可能通过连锁反应迅速扩大。','Các mạng này phụ thuộc mạnh vào nhau trong đời sống hằng ngày, nên một sự cố cục bộ có thể nhanh chóng lan rộng qua phản ứng dây chuyền.'),
('停电不仅让灯熄灭，还可能影响供水泵、手机基站、交通信号、医院设备和电子支付。','Mất điện không chỉ làm tắt đèn mà còn ảnh hưởng bơm nước, trạm di động, tín hiệu giao thông, thiết bị bệnh viện và thanh toán điện tử.'),
('洪水不仅损坏房屋，也可能阻断道路，使救护车无法到达，并导致食品和药品供应中断。','Lũ không chỉ làm hỏng nhà mà còn chặn đường, khiến xe cứu thương không đến được và làm gián đoạn thực phẩm, thuốc.'),
('所谓城市韧性，是指城市面对冲击时维持核心功能、保护居民，并在事后学习和调整的能力。','Khả năng chống chịu đô thị là năng lực duy trì chức năng cốt lõi, bảo vệ cư dân và học hỏi, điều chỉnh sau cú sốc.'),
('它并不意味着城市能够避免所有灾害，也不是简单地恢复到原来的状态。','Nó không có nghĩa thành phố tránh được mọi thảm họa hay chỉ khôi phục trạng thái cũ.'),
('如果原有系统本来就不公平、污染严重或容易失败，完全恢复反而会重新制造同样风险。','Nếu hệ thống cũ vốn bất công, ô nhiễm hoặc dễ thất bại, khôi phục hoàn toàn sẽ tái tạo cùng rủi ro.'),
('更积极的韧性强调“向前恢复”，也就是利用危机暴露的问题改善制度。','Khả năng chống chịu tích cực nhấn mạnh “phục hồi tiến lên”, tức dùng vấn đề lộ ra trong khủng hoảng để cải thiện thể chế.'),
('基础设施的冗余是重要原则之一。','Dự phòng hạ tầng là một nguyên tắc quan trọng.'),
('如果城市只有一个供水来源、一条主要通道或单一数据中心，效率可能很高，但任何故障都会造成巨大影响。','Nếu thành phố chỉ có một nguồn nước, một tuyến chính hoặc một trung tâm dữ liệu, hiệu quả có thể cao nhưng bất kỳ sự cố nào cũng gây tác động lớn.'),
('备用系统、分布式能源和多种交通方式会增加短期成本，却能降低全面瘫痪的概率。','Hệ thống dự phòng, năng lượng phân tán và nhiều phương thức giao thông tăng chi phí ngắn hạn nhưng giảm xác suất tê liệt toàn diện.'),
('多样性同样重要，因为不同系统对同一种冲击的反应并不相同。','Đa dạng cũng quan trọng vì các hệ thống phản ứng khác nhau trước cùng cú sốc.'),
('在公共交通中，地铁、公交、步行和自行车相互补充，可以在某一方式中断时提供替代。','Trong giao thông công cộng, metro, xe buýt, đi bộ và xe đạp bổ sung nhau, cung cấp thay thế khi một phương thức gián đoạn.'),
('但冗余和多样性不能只服务中心区。','Nhưng dự phòng và đa dạng không thể chỉ phục vụ khu trung tâm.'),
('低收入社区往往处在风险更高、投资更少的地方，灾害发生后也更难获得保险、储蓄和搬迁选择。','Cộng đồng thu nhập thấp thường ở nơi rủi ro cao, đầu tư ít và sau thiên tai khó có bảo hiểm, tiết kiệm hay lựa chọn di dời.'),
('如果韧性项目提高地价并迫使原居民离开，所谓安全改善就可能变成“绿色驱逐”。','Nếu dự án chống chịu làm tăng giá đất và buộc cư dân cũ rời đi, cải thiện an toàn có thể thành “trục xuất xanh”.'),
('规划必须把住房可负担性、租户保护和社区所有权纳入设计。','Quy hoạch phải đưa khả năng chi trả nhà ở, bảo vệ người thuê và sở hữu cộng đồng vào thiết kế.'),
('社会关系也是基础设施，虽然它不像桥梁和管道那样容易被看见。','Quan hệ xã hội cũng là hạ tầng dù không dễ thấy như cầu và đường ống.'),
('灾害中，邻居往往是最先提供信息、食物、交通和照护的人。','Trong thiên tai, hàng xóm thường là người đầu tiên cung cấp thông tin, thực phẩm, di chuyển và chăm sóc.'),
('长期缺乏信任的社区，即使拥有先进设备，也可能因为沟通失败而无法有效行动。','Cộng đồng thiếu niềm tin lâu dài dù có thiết bị tiên tiến vẫn có thể không hành động hiệu quả vì giao tiếp thất bại.'),
('社区组织、学校、宗教场所和地方商店可以成为平时建立联系、危机时传递资源的节点。','Tổ chức cộng đồng, trường, nơi tôn giáo và cửa hàng địa phương có thể là nút xây liên hệ lúc bình thường và truyền nguồn lực khi khủng hoảng.'),
('政府应在灾害前与这些组织合作，而不是只在紧急状态下临时寻找联系人。','Chính quyền nên hợp tác với các tổ chức này trước thiên tai, không phải chỉ tìm người liên hệ tạm thời khi khẩn cấp.'),
('信息系统需要可靠，也需要可理解。','Hệ thống thông tin cần đáng tin và dễ hiểu.'),
('警报如果只通过智能手机发送，会遗漏没有设备、网络不稳定或不熟悉技术的人。','Cảnh báo nếu chỉ gửi qua smartphone sẽ bỏ sót người không có thiết bị, mạng không ổn định hoặc không thạo công nghệ.'),
('多语言广播、社区志愿者、公共屏幕和传统媒体仍然不可缺少。','Phát thanh đa ngôn ngữ, tình nguyện viên cộng đồng, màn hình công cộng và truyền thông truyền thống vẫn không thể thiếu.'),
('信息过多也可能造成混乱，因此需要统一来源、清楚行动指引和及时纠错。','Quá nhiều thông tin cũng gây hỗn loạn, nên cần nguồn thống nhất, chỉ dẫn hành động rõ và sửa lỗi kịp thời.'),
('数据和模型能够帮助识别高风险区域，但它们往往依赖历史记录。','Dữ liệu và mô hình giúp nhận diện vùng rủi ro cao nhưng thường phụ thuộc hồ sơ lịch sử.'),
('在气候变化和快速城市化背景下，过去频率不一定代表未来。','Trong bối cảnh biến đổi khí hậu và đô thị hóa nhanh, tần suất quá khứ không nhất thiết đại diện tương lai.'),
('规划者需要使用不同情景，考虑极端但可能发生的事件，而不是只准备最常见情况。','Nhà quy hoạch cần dùng nhiều kịch bản, tính đến sự kiện cực đoan nhưng có thể xảy ra, không chỉ chuẩn bị cho trường hợp phổ biến nhất.'),
('同时，模型的假设和局限应向公众说明，避免技术图表替代民主讨论。','Đồng thời, giả định và giới hạn mô hình cần được giải thích cho công chúng để tránh biểu đồ kỹ thuật thay thế thảo luận dân chủ.'),
('灾后重建常面临速度与参与之间的矛盾。','Tái thiết sau thiên tai thường đối mặt mâu thuẫn giữa tốc độ và tham gia.'),
('受灾者急需住房和收入，快速行动非常重要；但如果为了速度跳过咨询，重建项目可能不符合真实需要。','Người bị nạn cần nhà và thu nhập khẩn cấp nên hành động nhanh rất quan trọng; nhưng nếu bỏ tư vấn vì tốc độ, dự án có thể không phù hợp nhu cầu thật.'),
('可以通过灾前制定参与框架、预先确认土地权利和建立透明采购规则来减少这种冲突。','Có thể giảm xung đột bằng khung tham gia trước thiên tai, xác nhận trước quyền đất và xây quy tắc mua sắm minh bạch.'),
('韧性评估不应只统计修复了多少公里道路，还要看最脆弱的人是否恢复了安全生活。','Đánh giá khả năng chống chịu không chỉ đếm bao nhiêu km đường đã sửa mà còn phải xem người dễ tổn thương nhất có khôi phục cuộc sống an toàn hay không.'),
('有些损失无法用金钱衡量，例如社区网络、文化场所和对家园的信任。','Một số mất mát không thể đo bằng tiền như mạng lưới cộng đồng, địa điểm văn hóa và niềm tin vào quê nhà.'),
('真正有韧性的城市不会把危机视为偶然中断，而会把日常维护、公平投资和持续学习当作安全的一部分。','Thành phố thực sự chống chịu không coi khủng hoảng là gián đoạn ngẫu nhiên mà xem bảo trì hằng ngày, đầu tư công bằng và học hỏi liên tục là một phần của an toàn.'),
('它承认复杂系统不可能被完全控制，却可以通过多样性、信任和可修正的制度减少灾害转化为灾难的可能。','Nó thừa nhận hệ thống phức tạp không thể kiểm soát hoàn toàn nhưng có thể giảm khả năng thiên tai biến thành thảm họa bằng đa dạng, niềm tin và thể chế có thể sửa.'),
],1500),
]


EXTENSIONS = {
'public-space': [
('儿童在公共空间中的活动尤其值得观察，因为他们通常会把台阶、墙边和空地转化成成年人没有预设的游戏场所。','Hoạt động của trẻ em trong không gian công cộng đặc biệt đáng quan sát vì chúng thường biến bậc thềm, mép tường và khoảng trống thành nơi chơi mà người lớn không dự tính.'),
('如果设计只强调整齐和秩序，禁止奔跑、停留或临时活动，空间就会失去适应真实生活的能力。','Nếu thiết kế chỉ nhấn mạnh gọn gàng và trật tự, cấm chạy, dừng hay hoạt động tạm thời, không gian sẽ mất khả năng thích ứng với đời sống thật.'),
('城市还应考虑气候变化带来的高温和强降雨，让公共空间能够提供遮阴、排水和短暂避难。','Thành phố còn cần tính đến nóng cực đoan và mưa lớn do biến đổi khí hậu, để không gian công cộng có thể tạo bóng mát, thoát nước và nơi trú tạm.'),
('这些功能平时改善舒适度，紧急情况下也能提高社区的安全。','Những chức năng này cải thiện sự thoải mái lúc bình thường và tăng an toàn cộng đồng khi khẩn cấp.'),
('商业活动可以为维护提供资金，但必须限制广告、噪声和对非消费者的排斥。','Hoạt động thương mại có thể cung cấp kinh phí bảo trì nhưng cần hạn chế quảng cáo, tiếng ồn và việc loại trừ người không tiêu dùng.'),
('如果一个人必须不断购买东西才能坐下或使用厕所，那么所谓公共性就已经被削弱。','Nếu một người phải liên tục mua hàng mới được ngồi hay dùng nhà vệ sinh, tính công cộng đã bị suy yếu.'),
('公共空间的公平还体现在谁有时间使用它，因为轮班劳动者、照护者和学生的作息并不相同。','Công bằng còn thể hiện ở ai có thời gian sử dụng, vì người làm ca, người chăm sóc và học sinh có lịch sinh hoạt khác nhau.'),
('延长部分设施开放时间、提供夜间照明并保证公共交通连接，可以让更多人真正受益。','Kéo dài giờ mở một số cơ sở, cung cấp ánh sáng ban đêm và kết nối giao thông công cộng giúp nhiều người thực sự hưởng lợi.')],
'ai-learning': [
('学生还应学会保存自己的草稿和修改记录，以便看清思路如何变化，而不是只保留最终文本。','Học sinh cũng nên lưu bản nháp và lịch sử chỉnh sửa để thấy tư duy thay đổi thế nào, thay vì chỉ giữ văn bản cuối.'),
('这种过程证据既能帮助教师评价学习，也能让学生发现自己在哪些环节过度依赖工具。','Bằng chứng quá trình vừa giúp giáo viên đánh giá việc học vừa giúp học sinh nhận ra khâu nào mình phụ thuộc công cụ quá mức.'),
('当系统给出多个答案时，学习者可以比较它们的假设、语气和遗漏，而不是只选择最流畅的一项。','Khi hệ thống đưa nhiều đáp án, người học có thể so sánh giả định, giọng điệu và điều bị bỏ sót thay vì chỉ chọn phương án trôi chảy nhất.'),
('课堂讨论还可以分析人工智能为什么会犯错，这比单纯告诉学生“不要相信”更能培养判断力。','Thảo luận trên lớp có thể phân tích vì sao AI mắc lỗi; cách này nuôi dưỡng phán đoán tốt hơn việc chỉ nói “đừng tin”.'),
('对于年幼学生，学校应更加谨慎，因为他们尚未形成稳定知识，难以识别看似合理的错误。','Với học sinh nhỏ tuổi, trường cần thận trọng hơn vì các em chưa có nền kiến thức ổn định để nhận ra lỗi có vẻ hợp lý.'),
('家长也需要了解工具的能力和限制，避免把使用时间多少简单等同于学习效果。','Phụ huynh cũng cần hiểu khả năng và giới hạn của công cụ, tránh đồng nhất thời gian sử dụng với hiệu quả học.'),
('未来的考试可能更重视现场解释、项目过程和口头答辩，以证明学生能够理解并承担自己的作品。','Kỳ thi tương lai có thể coi trọng giải thích tại chỗ, quá trình dự án và vấn đáp để chứng minh học sinh hiểu và chịu trách nhiệm với sản phẩm.'),
('无论评价形式怎样变化，教育的目标仍应是帮助人逐步获得不依赖即时提示也能思考和表达的能力。','Dù hình thức đánh giá thay đổi thế nào, mục tiêu giáo dục vẫn là giúp con người dần có năng lực suy nghĩ và biểu đạt mà không phụ thuộc gợi ý tức thời.')],
'aging': [
('数字化公共服务为生活带来便利，却也可能让不会使用智能设备的老人难以办理基本事务。','Dịch vụ công số mang lại tiện lợi nhưng cũng có thể khiến người già không biết dùng thiết bị thông minh khó làm thủ tục cơ bản.'),
('因此，线上渠道应保留人工帮助和线下选择，而不是把技术能力变成获得权利的前提。','Vì vậy, kênh trực tuyến cần giữ hỗ trợ con người và lựa chọn trực tiếp, không biến năng lực công nghệ thành điều kiện để có quyền lợi.'),
('医疗系统也应从单纯治疗疾病转向长期管理、康复和预防，帮助人们尽可能保持独立。','Hệ thống y tế cũng cần chuyển từ chỉ chữa bệnh sang quản lý dài hạn, phục hồi và phòng ngừa để giúp con người giữ độc lập tối đa.'),
('家庭医生、社区护士和居家服务之间如果缺少信息共享，老人就可能反复接受检查，却仍得不到连续照护。','Nếu bác sĩ gia đình, y tá cộng đồng và dịch vụ tại nhà thiếu chia sẻ thông tin, người già có thể bị kiểm tra lặp lại nhưng vẫn không được chăm sóc liên tục.'),
('社会还需要讨论孤独问题，因为缺少联系会影响心理健康，也会增加身体疾病风险。','Xã hội còn cần bàn về cô đơn vì thiếu kết nối ảnh hưởng sức khỏe tinh thần và làm tăng nguy cơ bệnh thể chất.'),
('提供可负担交通、社区课程和公共活动，比只在危机出现后提供短期帮助更有效。','Cung cấp giao thông vừa túi tiền, khóa học cộng đồng và hoạt động công hiệu quả hơn hỗ trợ ngắn hạn sau khủng hoảng.'),
('对衰老的积极理解并不是否认脆弱，而是承认人在需要帮助时仍然拥有选择、隐私和表达意见的权利。','Hiểu tích cực về lão hóa không phải phủ nhận sự mong manh mà thừa nhận người cần giúp vẫn có quyền lựa chọn, riêng tư và bày tỏ ý kiến.'),
('这种权利应体现在每天的服务细节里，而不只是写在政策文件中。','Quyền đó cần thể hiện trong chi tiết dịch vụ hằng ngày chứ không chỉ nằm trong văn bản chính sách.')],
'information-bubble': [
('学校和家庭还可以鼓励年轻人区分“我喜欢看”与“这对我理解问题有帮助”之间的差别。','Trường học và gia đình có thể khuyến khích người trẻ phân biệt “tôi thích xem” với “điều này giúp tôi hiểu vấn đề”.'),
('娱乐内容本身没有问题，但如果所有空闲时间都被连续播放占据，人们就很难形成主动阅读和深入思考的习惯。','Nội dung giải trí không có vấn đề, nhưng nếu mọi thời gian rảnh bị phát liên tục chiếm lấy, con người khó hình thành thói quen đọc chủ động và suy nghĩ sâu.'),
('平台可以设置自然停止点、使用时间提醒和按时间顺序查看的选项，帮助用户重新获得控制。','Nền tảng có thể tạo điểm dừng tự nhiên, nhắc thời gian sử dụng và tùy chọn xem theo thứ tự thời gian để giúp người dùng giành lại quyền kiểm soát.'),
('这些设计可能减少短期互动，却有助于建立更健康的长期关系。','Những thiết kế này có thể giảm tương tác ngắn hạn nhưng giúp xây quan hệ dài hạn lành mạnh hơn.'),
('研究推荐系统还需要访问真实数据，而企业常以商业秘密和隐私为由限制外部审查。','Nghiên cứu hệ thống đề xuất cần truy cập dữ liệu thật, trong khi doanh nghiệp thường hạn chế kiểm tra ngoài vì bí mật kinh doanh và riêng tư.'),
('合理制度可以要求提供经过匿名处理的数据、风险报告和独立测试，而不必公开所有用户信息。','Thể chế hợp lý có thể yêu cầu dữ liệu ẩn danh, báo cáo rủi ro và kiểm thử độc lập mà không phải công khai mọi thông tin người dùng.'),
('推荐技术不会消失，因此目标不是回到没有算法的过去，而是让算法在可以理解、质疑和选择的环境中运行。','Công nghệ đề xuất sẽ không biến mất; mục tiêu không phải trở lại quá khứ không thuật toán mà là để thuật toán vận hành trong môi trường có thể hiểu, chất vấn và lựa chọn.'),
('当用户能够看见规则并拥有退出方式时，个性化才可能成为服务，而不是隐藏的操纵。','Khi người dùng nhìn thấy quy tắc và có cách thoát, cá nhân hóa mới có thể là dịch vụ thay vì thao túng ẩn.')],
'craft': [
('旅游市场能够提高知名度，却也容易要求工匠快速生产统一、便宜并方便运输的商品。','Thị trường du lịch có thể tăng độ nhận biết nhưng cũng dễ buộc thợ sản xuất nhanh hàng đồng nhất, rẻ và dễ vận chuyển.'),
('如果这种需求长期主导生产，复杂技法和地方差异可能逐渐被简化。','Nếu nhu cầu này chi phối lâu dài, kỹ thuật phức tạp và khác biệt địa phương có thể dần bị đơn giản hóa.'),
('电商平台扩大了销售范围，但照片、包装、物流和售后也增加了工匠不熟悉的新劳动。','Thương mại điện tử mở rộng thị trường nhưng ảnh, đóng gói, logistics và hậu mãi cũng tạo thêm loại lao động mới mà thợ chưa quen.'),
('合作机构可以提供这些公共服务，让工匠把更多时间用于制作和教学。','Tổ chức hợp tác có thể cung cấp các dịch vụ chung để thợ dành nhiều thời gian hơn cho sản xuất và giảng dạy.'),
('知识产权制度对传统文化并不总是适用，因为许多图案由社区长期共同创造，无法归属于单一作者。','Chế độ sở hữu trí tuệ không phải lúc nào cũng phù hợp với văn hóa truyền thống vì nhiều hoa văn do cộng đồng cùng tạo qua thời gian dài, không thuộc một tác giả.'),
('因此，需要探索集体标识、地理来源认证和社区协议等更适合的保护方式。','Vì vậy, cần tìm các cách bảo vệ phù hợp hơn như nhãn hiệu tập thể, chứng nhận nguồn gốc địa lý và thỏa thuận cộng đồng.'),
('传承成果也不应只用销售额衡量，还要看年轻人是否愿意加入、核心知识是否保存，以及社区是否保持决定权。','Kết quả truyền nghề không nên chỉ đo bằng doanh số mà còn phải xem người trẻ có muốn tham gia, tri thức cốt lõi có được giữ và cộng đồng có còn quyền quyết định hay không.'),
('当经济、教育和文化目标能够相互支持时，传统手工艺才可能成为活着的实践，而不是被复制的符号。','Khi mục tiêu kinh tế, giáo dục và văn hóa hỗ trợ lẫn nhau, nghề thủ công mới có thể là thực hành sống chứ không phải biểu tượng bị sao chép.')],
'work-meaning': [
('企业在引入自动化之前，还应评估它对工作质量的影响，而不只是计算能够减少多少岗位。','Trước khi tự động hóa, doanh nghiệp cần đánh giá ảnh hưởng đến chất lượng công việc chứ không chỉ tính giảm được bao nhiêu vị trí.'),
('如果系统让劳动者失去理解完整流程的机会，他们在出现异常时反而更难处理。','Nếu hệ thống khiến người lao động mất cơ hội hiểu toàn bộ quy trình, họ sẽ khó xử lý hơn khi có bất thường.'),
('保留一定的人工练习、轮岗和解释权，可以避免组织能力被表面效率逐渐掏空。','Giữ một mức thực hành thủ công, luân chuyển và quyền giải thích có thể ngăn năng lực tổ chức bị hiệu quả bề mặt làm rỗng dần.'),
('工会和专业协会也需要参与技术采购与部署，因为一线人员最了解哪些指标会扭曲实际工作。','Công đoàn và hiệp hội nghề nghiệp cần tham gia mua sắm và triển khai công nghệ vì người tuyến đầu hiểu nhất chỉ số nào làm méo công việc thật.'),
('公共部门使用算法时尤其要谨慎，因为错误决定可能影响福利、教育、医疗甚至人身自由。','Khu vực công dùng thuật toán cần đặc biệt thận trọng vì quyết định sai có thể ảnh hưởng phúc lợi, giáo dục, y tế và cả tự do cá nhân.'),
('受影响者应有权获得理由、要求人工复核并纠正错误数据。','Người bị ảnh hưởng cần có quyền nhận lý do, yêu cầu xem xét bởi con người và sửa dữ liệu sai.'),
('劳动政策还应考虑无偿照护者，因为技术转型可能把更多服务责任转移到家庭。','Chính sách lao động còn cần tính người chăm sóc không lương vì chuyển đổi công nghệ có thể chuyển thêm trách nhiệm dịch vụ về gia đình.'),
('如果公共服务数字化后减少线下支持，节省的行政成本可能由老人、残障者和家属以时间承担。','Nếu số hóa dịch vụ công làm giảm hỗ trợ trực tiếp, chi phí hành chính tiết kiệm được có thể do người già, người khuyết tật và gia đình gánh bằng thời gian.'),
('因此，评价技术效率必须计算被隐藏和转移的劳动，而不能只看机构账面。','Vì vậy, đánh giá hiệu quả công nghệ phải tính cả lao động bị che giấu và chuyển giao, không thể chỉ nhìn sổ sách cơ quan.')],
'climate-fairness': [
('粮食系统也是气候公平的重要领域，因为农民既承受极端天气，又常缺少改变生产方式所需的资金。','Hệ thống lương thực cũng là lĩnh vực quan trọng của công bằng khí hậu vì nông dân vừa chịu thời tiết cực đoan vừa thường thiếu vốn để đổi cách sản xuất.'),
('要求小农立即承担全部转型成本，可能导致土地集中和生计丧失。','Yêu cầu nông hộ nhỏ lập tức gánh toàn bộ chi phí chuyển đổi có thể dẫn đến tập trung đất và mất sinh kế.'),
('长期信贷、农业保险、技术服务和公平采购，可以让减排与农村发展相互支持。','Tín dụng dài hạn, bảo hiểm nông nghiệp, dịch vụ kỹ thuật và mua sắm công bằng có thể giúp giảm phát thải hỗ trợ phát triển nông thôn.'),
('城市中的绿色改造也需要防止租金上涨，否则原本承受污染的人可能在环境改善后被迫搬走。','Cải tạo xanh đô thị cũng cần ngăn giá thuê tăng, nếu không người từng chịu ô nhiễm có thể bị buộc chuyển đi sau khi môi trường tốt lên.'),
('把社区土地信托、保障性住房和能源补贴结合起来，能够减少这种矛盾。','Kết hợp quỹ đất cộng đồng, nhà ở bảo đảm và trợ cấp năng lượng có thể giảm mâu thuẫn này.'),
('此外，气候政策应关注性别差异，因为照护责任、财产权和灾后资源分配常使女性承担不同风险。','Ngoài ra, chính sách khí hậu cần chú ý khác biệt giới vì trách nhiệm chăm sóc, quyền tài sản và phân phối nguồn lực sau thiên tai thường khiến phụ nữ chịu rủi ro khác.'),
('收集分类数据并让女性参与决策，可以避免所谓中性方案重复既有不平等。','Thu thập dữ liệu phân loại và để phụ nữ tham gia quyết định giúp tránh phương án tưởng trung tính lặp lại bất bình đẳng sẵn có.'),
('公平不是完成减排以后再考虑的附加条件，而是决定政策能否被接受、执行和长期维持的核心。','Công bằng không phải điều kiện phụ được xét sau khi giảm phát thải, mà là cốt lõi quyết định chính sách có được chấp nhận, thực hiện và duy trì lâu dài hay không.')],
'public-memory': [
('旅游产业也会塑造公共记忆，因为城市常把复杂历史压缩成容易消费的路线和故事。','Du lịch cũng định hình ký ức công cộng vì thành phố thường nén lịch sử phức tạp thành tuyến và câu chuyện dễ tiêu dùng.'),
('如果痛苦经验只被包装成景点，受影响群体可能再次失去解释自身历史的权力。','Nếu trải nghiệm đau khổ chỉ bị đóng gói thành điểm tham quan, nhóm bị ảnh hưởng có thể lại mất quyền giải thích lịch sử của mình.'),
('纪念场所应与社区合作，说明收入用途，并避免把创伤转化成猎奇娱乐。','Địa điểm tưởng niệm nên hợp tác với cộng đồng, giải thích cách dùng doanh thu và tránh biến tổn thương thành giải trí tò mò.'),
('家庭档案同样值得保护，因为信件、照片和日常物品能够展示宏大事件如何进入普通生活。','Kho tư liệu gia đình cũng đáng được bảo vệ vì thư, ảnh và vật dụng hằng ngày cho thấy sự kiện lớn đi vào đời thường thế nào.'),
('公共机构可以提供数字化与保存支持，同时让所有者保留对访问范围的决定。','Cơ quan công có thể hỗ trợ số hóa và bảo quản đồng thời để chủ sở hữu giữ quyền quyết định phạm vi truy cập.'),
('当代社会还会产生新的记忆争议，例如网络事件应该保存多久，删除权与公共利益如何平衡。','Xã hội hiện đại còn tạo tranh cãi ký ức mới như sự kiện trên mạng nên được lưu bao lâu và cân bằng quyền xóa với lợi ích công ra sao.'),
('一个人在年轻时发布的错误言论，不应必然成为终身标签；但涉及公共责任的记录也不能任意消失。','Phát ngôn sai lúc trẻ không nhất thiết phải thành nhãn suốt đời, nhưng hồ sơ liên quan trách nhiệm công cũng không thể tùy ý biến mất.'),
('这要求根据身份、影响和时间制定细致规则，而不是用永久保存或彻底删除处理所有情况。','Điều này đòi hỏi quy tắc tinh tế theo danh tính, tác động và thời gian, thay vì dùng lưu vĩnh viễn hoặc xóa sạch cho mọi trường hợp.'),
('公共记忆最终是一种关系实践：活着的人不断与过去对话，并决定哪些责任应被带入未来。','Ký ức công cộng cuối cùng là một thực hành quan hệ: người sống liên tục đối thoại với quá khứ và quyết định trách nhiệm nào cần mang vào tương lai.')],
'science-uncertainty': [
('专家之间出现分歧时，媒体不应只追求“双方各一句”的表面对称，而应说明各自证据的数量与质量。','Khi chuyên gia bất đồng, truyền thông không nên chỉ theo đuổi đối xứng bề mặt “mỗi bên một câu” mà cần giải thích số lượng và chất lượng bằng chứng của mỗi bên.'),
('少数意见有时后来会被证明正确，但它并不会仅因为是少数就自动更勇敢或更可靠。','Ý kiến thiểu số đôi khi về sau được chứng minh đúng, nhưng không tự động dũng cảm hay đáng tin chỉ vì là thiểu số.'),
('判断争议需要查看研究是否重复、方法是否透明，以及结论是否经得起独立检验。','Đánh giá tranh cãi cần xem nghiên cứu có lặp lại được, phương pháp có minh bạch và kết luận có chịu được kiểm chứng độc lập hay không.'),
('政府还应建立利益冲突申报制度，让公众知道顾问与企业、政治组织之间的关系。','Chính phủ còn nên có chế độ khai báo xung đột lợi ích để công chúng biết quan hệ giữa cố vấn với doanh nghiệp, tổ chức chính trị.'),
('利益关系并不必然使研究无效，但隐藏关系会削弱信任，也妨碍他人判断偏差风险。','Quan hệ lợi ích không nhất thiết làm nghiên cứu vô hiệu, nhưng giấu quan hệ sẽ làm suy yếu niềm tin và cản người khác đánh giá nguy cơ thiên lệch.'),
('在教育中，学生应练习阅读图表、理解概率并区分相关与因果，而不是只记住结论。','Trong giáo dục, học sinh nên luyện đọc biểu đồ, hiểu xác suất và phân biệt tương quan với nhân quả thay vì chỉ nhớ kết luận.'),
('这种能力能帮助公众在危机之外也更理性地处理健康、经济和环境信息。','Năng lực này giúp công chúng xử lý thông tin sức khỏe, kinh tế và môi trường lý tính hơn cả ngoài khủng hoảng.'),
('科学素养的目的不是让每个人都成为专家，而是让人知道何时需要专家、如何提出问题以及怎样判断证据。','Mục đích của hiểu biết khoa học không phải biến mọi người thành chuyên gia mà là biết khi nào cần chuyên gia, hỏi thế nào và đánh giá bằng chứng ra sao.'),
('当制度允许公开纠错而不把修正视为软弱时，科学与民主都更有可能保持活力。','Khi thể chế cho phép sửa lỗi công khai mà không coi điều chỉnh là yếu đuối, cả khoa học và dân chủ đều có khả năng giữ sức sống hơn.')],
'urban-resilience': [
('城市财政安排会直接影响韧性，因为预防性维护通常不如新建工程容易获得政治关注。','Sắp xếp tài chính đô thị ảnh hưởng trực tiếp đến khả năng chống chịu vì bảo trì phòng ngừa thường khó thu hút chú ý chính trị bằng công trình mới.'),
('管道检查、树木护理和人员培训看起来普通，却可能比灾后昂贵重建更有效。','Kiểm tra đường ống, chăm cây và đào tạo nhân sự trông bình thường nhưng có thể hiệu quả hơn tái thiết đắt đỏ sau thiên tai.'),
('预算制度应为长期维护保留稳定资金，并公开设施状况与延期维修的风险。','Chế độ ngân sách nên dành kinh phí ổn định cho bảo trì dài hạn và công khai tình trạng cơ sở cùng rủi ro trì hoãn sửa chữa.'),
('保险可以分散损失，但若保费完全按风险定价，最危险地区的居民可能恰好最无力购买。','Bảo hiểm có thể phân tán tổn thất, nhưng nếu phí hoàn toàn theo rủi ro, cư dân vùng nguy hiểm nhất có thể lại ít khả năng mua nhất.'),
('公共保险、风险减缓补贴和有计划的搬迁需要结合，而不能只依赖市场。','Bảo hiểm công, trợ cấp giảm rủi ro và di dời có kế hoạch cần kết hợp, không thể chỉ dựa vào thị trường.'),
('搬迁政策必须尊重社区联系和生计来源，并让居民参与选择地点与补偿方式。','Chính sách di dời phải tôn trọng liên kết cộng đồng, nguồn sinh kế và cho cư dân tham gia chọn nơi cùng cách bồi thường.'),
('对历史建筑和文化景观的保护也需要纳入风险规划，因为它们承载身份与集体记忆。','Bảo vệ công trình lịch sử và cảnh quan văn hóa cũng cần đưa vào quy hoạch rủi ro vì chúng chứa bản sắc và ký ức tập thể.'),
('有些设施无法完全加固，就需要数字记录、可移动藏品和灾后修复方案。','Một số cơ sở không thể gia cố hoàn toàn thì cần hồ sơ số, hiện vật có thể di chuyển và phương án phục hồi sau thiên tai.'),
('跨行政区域的合作同样关键，因为河流、交通和电网不会在城市边界停止。','Hợp tác liên vùng hành chính cũng rất quan trọng vì sông, giao thông và lưới điện không dừng ở ranh giới thành phố.'),
('如果上游与下游、中心与郊区各自规划，局部安全可能以增加其他地区风险为代价。','Nếu thượng nguồn, hạ nguồn, trung tâm và ngoại ô tự quy hoạch riêng, an toàn cục bộ có thể đổi bằng tăng rủi ro nơi khác.'),
('区域数据共享、联合演练和明确责任能够减少危机中的协调失败。','Chia sẻ dữ liệu vùng, diễn tập chung và trách nhiệm rõ có thể giảm thất bại phối hợp trong khủng hoảng.')],
}


def enrich(items):
    out=[]
    for slug,title,topic,pairs,target in items:
        out.append((slug,title,topic,pairs + EXTENSIONS.get(slug, []),target))
    return out


def write(level: int, display: str, target: int, items):
    passages = [make(level, slug, title, topic, target, pairs) for slug,title,topic,pairs,_ in items]
    payload = {
        'meta': {
            'level': str(level), 'displayLevel': display, 'version': '7.0.0',
            'targetCharacters': target, 'passageCount': len(passages),
            'description': 'Bài đọc biên soạn theo độ dài mục tiêu, có pinyin, highlight từ và dịch từng câu.'
        },
        'passages': passages
    }
    (READING / f'hsk{level}.json').write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
    return passages

if __name__ == '__main__':
    p6 = write(6, '6', 1000, enrich(HSK6))
    p7 = write(7, '7–9', 1500, enrich(HSK7))
    meta_path = READING / 'meta.json'
    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    meta['version'] = '7.0.0'
    meta['levels']['6'] = {'passages': len(p6), 'lengths': [p['actualCharacters'] for p in p6]}
    meta['levels']['7'] = {'passages': len(p7), 'lengths': [p['actualCharacters'] for p in p7]}
    meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding='utf-8')
    print('HSK6:', [p['actualCharacters'] for p in p6])
    print('HSK7:', [p['actualCharacters'] for p in p7])
